/* eslint-disable */

// This file was automatically generated by TailorKit.
// Documentation: https://tailorkit.dev/docs

// Do not make changes to this file directly, as it will be overwritten.
// Exclude this file from linting and formatting to avoid checking generated code.

import { createRemoteComponent } from "tailorkit/client";

import { callTool } from "tailorkit/client";

export interface ViewPropsByPath {
  "/": {
    context: {
      user: {
        id: string;
        name: string;
      };
    };
  };
  "/customers": {
    context: {
      user: {
        id: string;
        name: string;
      };
    } & {
      customers: {
        id: string;
        name: string;
      }[];
    };
  };
  "/customers/detail": {
    context: {
      user: {
        id: string;
        name: string;
      };
    } & {
      customers: {
        id: string;
        name: string;
      }[];
    } & {
      customer: {
        id: string;
        name: string;
      };
    };
  };
}

declare module "tailorkit/client" {
  interface TailorKitViews extends ViewPropsByPath {}
  interface TailorKitSlots {
    page: { views: "/"; multiple: true };
    panel: { views: "/" | "/customers" | "/customers/detail"; multiple: false };
    navbar: { views: "/"; multiple: false };
  }
}

export type ViewPath = keyof ViewPropsByPath & string;
export type ViewProps<TPath extends ViewPath> = ViewPropsByPath[TPath];
export type TailorKitTools = {
  echo: (input: string) => Promise<string>;
  navigation: {
    openCustomer: (input: { customerId: string }) => Promise<string>;
  };
};
export type TailorKitBackendTools = {
  echo: (input: string) => Promise<string>;
};
declare module "tailorkit/client" {
  interface TailorKitServerTools extends TailorKitBackendTools {}
}
export const tools = {
  echo: (input?: unknown) => callTool("server", "echo", input),
  navigation: {
    openCustomer: (input?: unknown) => callTool("client", "navigation.openCustomer", input),
  },
} as TailorKitTools;

export type Breakpoint = "base" | "sm" | "md" | "lg" | "xl" | "2xl";
export type Responsive<TValue> = TValue | Partial<Record<Breakpoint, TValue>>;
export type Background = Responsive<"muted" | "surface">;
export type Basis = Responsive<
  | "0"
  | "1/2"
  | "1/3"
  | "2/3"
  | "1/4"
  | "2/4"
  | "3/4"
  | "1/5"
  | "2/5"
  | "3/5"
  | "4/5"
  | "1/6"
  | "2/6"
  | "3/6"
  | "4/6"
  | "5/6"
  | "1/12"
  | "2/12"
  | "3/12"
  | "4/12"
  | "5/12"
  | "6/12"
  | "7/12"
  | "8/12"
  | "9/12"
  | "10/12"
  | "11/12"
  | "full"
  | "min"
  | "max"
  | "fit"
>;
export type Border = Responsive<"solid" | "dashed" | "dotted" | "double">;
export type BorderColor = Responsive<"default">;
export type Grow = Responsive<"0" | "1">;
export type Height = Responsive<
  | "0"
  | "1/2"
  | "1/3"
  | "2/3"
  | "1/4"
  | "2/4"
  | "3/4"
  | "1/5"
  | "2/5"
  | "3/5"
  | "4/5"
  | "1/6"
  | "2/6"
  | "3/6"
  | "4/6"
  | "5/6"
  | "1/12"
  | "2/12"
  | "3/12"
  | "4/12"
  | "5/12"
  | "6/12"
  | "7/12"
  | "8/12"
  | "9/12"
  | "10/12"
  | "11/12"
  | "full"
  | "min"
  | "max"
  | "fit"
>;
export type Margin = Responsive<"none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl">;
export type MinHeight = Responsive<
  | "0"
  | "1/2"
  | "1/3"
  | "2/3"
  | "1/4"
  | "2/4"
  | "3/4"
  | "1/5"
  | "2/5"
  | "3/5"
  | "4/5"
  | "1/6"
  | "2/6"
  | "3/6"
  | "4/6"
  | "5/6"
  | "1/12"
  | "2/12"
  | "3/12"
  | "4/12"
  | "5/12"
  | "6/12"
  | "7/12"
  | "8/12"
  | "9/12"
  | "10/12"
  | "11/12"
  | "full"
  | "min"
  | "max"
  | "fit"
>;
export type MinWidth = Responsive<
  | "0"
  | "1/2"
  | "1/3"
  | "2/3"
  | "1/4"
  | "2/4"
  | "3/4"
  | "1/5"
  | "2/5"
  | "3/5"
  | "4/5"
  | "1/6"
  | "2/6"
  | "3/6"
  | "4/6"
  | "5/6"
  | "1/12"
  | "2/12"
  | "3/12"
  | "4/12"
  | "5/12"
  | "6/12"
  | "7/12"
  | "8/12"
  | "9/12"
  | "10/12"
  | "11/12"
  | "full"
  | "min"
  | "max"
  | "fit"
>;
export type Overflow = Responsive<"visible" | "hidden" | "clip" | "scroll" | "auto">;
export type OverflowWrap = Responsive<"normal" | "breakWord" | "anywhere">;
export type Padding = Responsive<"none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl">;
export type Radius = Responsive<"none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl">;
export type Shrink = Responsive<"0" | "1">;
export type TextAlign = Responsive<"left" | "right" | "start" | "end" | "center" | "justify">;
export type TextColor = Responsive<"default">;
export type TextOverflow = Responsive<"clip" | "ellipsis">;
export type TextTransform = Responsive<"capitalize" | "uppercase" | "lowercase" | "none">;
export type Width = Responsive<
  | "0"
  | "1/2"
  | "1/3"
  | "2/3"
  | "1/4"
  | "2/4"
  | "3/4"
  | "1/5"
  | "2/5"
  | "3/5"
  | "4/5"
  | "1/6"
  | "2/6"
  | "3/6"
  | "4/6"
  | "5/6"
  | "1/12"
  | "2/12"
  | "3/12"
  | "4/12"
  | "5/12"
  | "6/12"
  | "7/12"
  | "8/12"
  | "9/12"
  | "10/12"
  | "11/12"
  | "full"
  | "min"
  | "max"
  | "fit"
>;
export type Align = Responsive<"start" | "center" | "end" | "stretch">;
export type Direction = Responsive<"row" | "column">;
export type Gap = Responsive<"none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl">;
export type Justify = Responsive<"start" | "center" | "end" | "between">;
export type Wrap = Responsive<"wrap" | "nowrap" | "wrap-reverse">;
export type Columns = Responsive<1 | 2 | 3 | 4 | 6 | 12>;

export interface BoxProps {
  background?: Background;
  basis?: Basis;
  border?: Border;
  borderColor?: BorderColor;
  grow?: Grow;
  height?: Height;
  margin?: Margin;
  minHeight?: MinHeight;
  minWidth?: MinWidth;
  overflow?: Overflow;
  overflowWrap?: OverflowWrap;
  padding?: Padding;
  radius?: Radius;
  shrink?: Shrink;
  textAlign?: TextAlign;
  textColor?: TextColor;
  textOverflow?: TextOverflow;
  textTransform?: TextTransform;
  width?: Width;
}

export const Box = /* @__PURE__ */ createRemoteComponent<BoxProps, true>("Box", {
  children: true,
});

export interface FlexProps {
  background?: Background;
  basis?: Basis;
  border?: Border;
  borderColor?: BorderColor;
  grow?: Grow;
  height?: Height;
  margin?: Margin;
  minHeight?: MinHeight;
  minWidth?: MinWidth;
  overflow?: Overflow;
  overflowWrap?: OverflowWrap;
  padding?: Padding;
  radius?: Radius;
  shrink?: Shrink;
  textAlign?: TextAlign;
  textColor?: TextColor;
  textOverflow?: TextOverflow;
  textTransform?: TextTransform;
  width?: Width;
  align?: Align;
  direction?: Direction;
  gap?: Gap;
  justify?: Justify;
  wrap?: Wrap;
}

export const Flex = /* @__PURE__ */ createRemoteComponent<FlexProps, true>("Flex", {
  children: true,
});

export interface GridProps {
  background?: Background;
  basis?: Basis;
  border?: Border;
  borderColor?: BorderColor;
  grow?: Grow;
  height?: Height;
  margin?: Margin;
  minHeight?: MinHeight;
  minWidth?: MinWidth;
  overflow?: Overflow;
  overflowWrap?: OverflowWrap;
  padding?: Padding;
  radius?: Radius;
  shrink?: Shrink;
  textAlign?: TextAlign;
  textColor?: TextColor;
  textOverflow?: TextOverflow;
  textTransform?: TextTransform;
  width?: Width;
  columns?: Columns;
  gap?: Gap;
}

export const Grid = /* @__PURE__ */ createRemoteComponent<GridProps, true>("Grid", {
  children: true,
});

export interface InlineProps {
  background?: Background;
  borderColor?: BorderColor;
  margin?: Margin;
  overflowWrap?: OverflowWrap;
  padding?: Padding;
  radius?: Radius;
  textAlign?: TextAlign;
  textColor?: TextColor;
  textOverflow?: TextOverflow;
  textTransform?: TextTransform;
}

export const Inline = /* @__PURE__ */ createRemoteComponent<InlineProps, true>("Inline", {
  children: true,
});

export interface ButtonProps {
  size?: "default" | "sm" | "lg" | "icon" | "icon-sm" | "icon-lg";
  variant?: "default" | "secondary" | "ghost" | "outline" | "destructive";
  onClick?: () => void;
}

export const Button = /* @__PURE__ */ createRemoteComponent<ButtonProps, true>("Button", {
  children: true,
  callbacks: { onClick: 0 },
});

export interface TabsProps {
  value?: string;
  onValueChange?: (input: { value: string }) => void;
}

export const Tabs = /* @__PURE__ */ createRemoteComponent<TabsProps, true>("Tabs", {
  children: true,
  callbacks: { onValueChange: 1 },
});

export interface TabsListProps {}

export const TabsList = /* @__PURE__ */ createRemoteComponent<TabsListProps, true>("TabsList", {
  children: true,
});

export interface TabsTabProps {
  value?: string;
}

export const TabsTab = /* @__PURE__ */ createRemoteComponent<TabsTabProps, true>("TabsTab", {
  children: true,
});

export interface TabsPanelProps {
  value?: string;
}

export const TabsPanel = /* @__PURE__ */ createRemoteComponent<TabsPanelProps, true>("TabsPanel", {
  children: true,
});

export interface InputProps {
  value?: string;
  onValueChange?: (input: { value: string }) => void;
}

export const Input = /* @__PURE__ */ createRemoteComponent<InputProps, true>("Input", {
  children: true,
  callbacks: { onValueChange: 1 },
});

export interface TextAreaProps {
  value?: string;
  size?: "sm" | "default" | "lg" | number;
  onValueChange?: (input: { value: string }) => void;
}

export const TextArea = /* @__PURE__ */ createRemoteComponent<TextAreaProps, true>("TextArea", {
  children: true,
  callbacks: { onValueChange: 1 },
});
