// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  ServerSentEventsResult,
  TDataShape,
} from "./client/index.js";
import { client } from "./client.gen.js";
import type {
  AppAgentChatData,
  AppAgentChatResponse,
  AppAgentChatResponses,
  AppsCreateData,
  AppsCreateResponses,
  AppsDeleteData,
  AppsDeleteResponses,
  AppsDeployData,
  AppsDeployResponses,
  AppsGetData,
  AppsGetResponses,
  AppsListData,
  AppsListResponses,
  AppsRuntimeSessionData,
  AppsRuntimeSessionResponses,
  AppsUpdateData,
  AppsUpdateResponses,
  CliAuthApproveData,
  CliAuthApproveResponses,
  CliAuthDenyData,
  CliAuthDenyResponses,
  CliAuthPollData,
  CliAuthPollResponses,
  CliAuthStartData,
  CliAuthStartResponses,
  CliAuthVerifyTokenData,
  CliAuthVerifyTokenResponses,
  DeploymentsCreateData,
  DeploymentsCreateResponses,
  DeploymentsGetData,
  DeploymentsGetResponses,
  DeploymentsListData,
  DeploymentsListResponses,
  DeploymentsPublishData,
  DeploymentsPublishResponses,
  DeploymentsRuntimeData,
  DeploymentsRuntimeResponses,
  PreviewAcceptData,
  PreviewAcceptedData,
  PreviewAcceptedResponses,
  PreviewAcceptResponses,
  PreviewInvitationData,
  PreviewInvitationResponses,
  PreviewStartData,
  PreviewStartResponses,
  PreviewStopData,
  PreviewStopResponses,
} from "./types.gen.js";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const appAgentChat = <ThrowOnError extends boolean = false>(
  options: Options<AppAgentChatData, ThrowOnError, AppAgentChatResponse>,
): Promise<ServerSentEventsResult<AppAgentChatResponses>> =>
  (options.client ?? client).sse.post<AppAgentChatResponses, unknown, ThrowOnError>({
    url: "/app-agent/chat",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const appsRuntimeSession = <ThrowOnError extends boolean = false>(
  options: Options<AppsRuntimeSessionData, ThrowOnError>,
): RequestResult<AppsRuntimeSessionResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<AppsRuntimeSessionResponses, unknown, ThrowOnError>({
    url: "/apps/{appId}/runtime/session",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const appsList = <ThrowOnError extends boolean = false>(
  options: Options<AppsListData, ThrowOnError>,
): RequestResult<AppsListResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<AppsListResponses, unknown, ThrowOnError>({
    url: "/apps/list",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const appsGet = <ThrowOnError extends boolean = false>(
  options: Options<AppsGetData, ThrowOnError>,
): RequestResult<AppsGetResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<AppsGetResponses, unknown, ThrowOnError>({
    url: "/apps/{appId}/lookup",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const appsCreate = <ThrowOnError extends boolean = false>(
  options: Options<AppsCreateData, ThrowOnError>,
): RequestResult<AppsCreateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<AppsCreateResponses, unknown, ThrowOnError>({
    url: "/apps",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const appsDelete = <ThrowOnError extends boolean = false>(
  options: Options<AppsDeleteData, ThrowOnError>,
): RequestResult<AppsDeleteResponses, unknown, ThrowOnError> =>
  (options.client ?? client).delete<AppsDeleteResponses, unknown, ThrowOnError>({
    url: "/apps/{appId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const appsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<AppsUpdateData, ThrowOnError>,
): RequestResult<AppsUpdateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).put<AppsUpdateResponses, unknown, ThrowOnError>({
    url: "/apps/{appId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const appsDeploy = <ThrowOnError extends boolean = false>(
  options: Options<AppsDeployData, ThrowOnError>,
): RequestResult<AppsDeployResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<AppsDeployResponses, unknown, ThrowOnError>({
    url: "/apps/{appId}/deploy",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const cliAuthApprove = <ThrowOnError extends boolean = false>(
  options: Options<CliAuthApproveData, ThrowOnError>,
): RequestResult<CliAuthApproveResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<CliAuthApproveResponses, unknown, ThrowOnError>({
    url: "/cli-auth/approve",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const cliAuthDeny = <ThrowOnError extends boolean = false>(
  options: Options<CliAuthDenyData, ThrowOnError>,
): RequestResult<CliAuthDenyResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<CliAuthDenyResponses, unknown, ThrowOnError>({
    url: "/cli-auth/deny",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const cliAuthPoll = <ThrowOnError extends boolean = false>(
  options: Options<CliAuthPollData, ThrowOnError>,
): RequestResult<CliAuthPollResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<CliAuthPollResponses, unknown, ThrowOnError>({
    url: "/cli-auth/poll",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const cliAuthStart = <ThrowOnError extends boolean = false>(
  options: Options<CliAuthStartData, ThrowOnError>,
): RequestResult<CliAuthStartResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<CliAuthStartResponses, unknown, ThrowOnError>({
    url: "/cli-auth/start",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const cliAuthVerifyToken = <ThrowOnError extends boolean = false>(
  options: Options<CliAuthVerifyTokenData, ThrowOnError>,
): RequestResult<CliAuthVerifyTokenResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<CliAuthVerifyTokenResponses, unknown, ThrowOnError>({
    url: "/cli-auth/verify-token",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const deploymentsList = <ThrowOnError extends boolean = false>(
  options: Options<DeploymentsListData, ThrowOnError>,
): RequestResult<DeploymentsListResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<DeploymentsListResponses, unknown, ThrowOnError>({
    url: "/deployments/list",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const deploymentsGet = <ThrowOnError extends boolean = false>(
  options: Options<DeploymentsGetData, ThrowOnError>,
): RequestResult<DeploymentsGetResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<DeploymentsGetResponses, unknown, ThrowOnError>({
    url: "/deployments/{deploymentId}/lookup",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const deploymentsCreate = <ThrowOnError extends boolean = false>(
  options: Options<DeploymentsCreateData, ThrowOnError>,
): RequestResult<DeploymentsCreateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<DeploymentsCreateResponses, unknown, ThrowOnError>({
    url: "/deployments",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const deploymentsPublish = <ThrowOnError extends boolean = false>(
  options: Options<DeploymentsPublishData, ThrowOnError>,
): RequestResult<DeploymentsPublishResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<DeploymentsPublishResponses, unknown, ThrowOnError>({
    url: "/deployments/{deploymentId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const deploymentsRuntime = <ThrowOnError extends boolean = false>(
  options: Options<DeploymentsRuntimeData, ThrowOnError>,
): RequestResult<DeploymentsRuntimeResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<DeploymentsRuntimeResponses, unknown, ThrowOnError>({
    url: "/apps/{appId}/runtime",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const previewStart = <ThrowOnError extends boolean = false>(
  options: Options<PreviewStartData, ThrowOnError>,
): RequestResult<PreviewStartResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<PreviewStartResponses, unknown, ThrowOnError>({
    url: "/preview/start",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const previewStop = <ThrowOnError extends boolean = false>(
  options: Options<PreviewStopData, ThrowOnError>,
): RequestResult<PreviewStopResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<PreviewStopResponses, unknown, ThrowOnError>({
    url: "/preview/{sessionId}/stop",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const previewInvitation = <ThrowOnError extends boolean = false>(
  options: Options<PreviewInvitationData, ThrowOnError>,
): RequestResult<PreviewInvitationResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<PreviewInvitationResponses, unknown, ThrowOnError>({
    url: "/preview/shares/{shareId}",
    ...options,
  });

export const previewAccept = <ThrowOnError extends boolean = false>(
  options: Options<PreviewAcceptData, ThrowOnError>,
): RequestResult<PreviewAcceptResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<PreviewAcceptResponses, unknown, ThrowOnError>({
    url: "/preview/shares/{shareId}/accept",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const previewAccepted = <ThrowOnError extends boolean = false>(
  options: Options<PreviewAcceptedData, ThrowOnError>,
): RequestResult<PreviewAcceptedResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<PreviewAcceptedResponses, unknown, ThrowOnError>({
    url: "/preview/grants/resolve",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
