// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://tailorkit.dev/api/platform" | (string & {});
};

export type AppsListData = {
  body?: never;
  path?: never;
  query: {
    page?: number;
    pageSize?: number;
    scope: {
      [key: string]: string;
    };
  };
  url: "/apps";
};

export type AppsListResponses = {
  /**
   * OK
   */
  200: {
    items: Array<{
      id: string;
      publicId: string;
      projectId: string;
      scope: {
        [key: string]: string;
      };
      name: string;
      description: string | null;
      currentDeploymentId: string | null;
      createdAt: string;
      updatedAt: string;
      currentDeployment: {
        id: string;
        publicId: string;
        appId: string;
        status: "uploading" | "deploying" | "verifying" | "published";
        clientEntryFileId: string | null;
        logoLightFileId: string | null;
        logoDarkFileId: string | null;
        logoLightPath: string | null;
        logoDarkPath: string | null;
        createdAt: string;
        updatedAt: string;
      } | null;
      clientPath?: string;
      logoPaths?: {
        dark?: string;
        light?: string;
      };
    }>;
    pagination: {
      hasMore: boolean;
      page: number;
      pageSize: number;
    };
  };
};

export type AppsListResponse = AppsListResponses[keyof AppsListResponses];

export type AppsCreateData = {
  body: {
    name: string;
    description: string | null;
    scope: {
      [key: string]: string;
    };
  };
  path?: never;
  query?: never;
  url: "/apps";
};

export type AppsCreateResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    publicId: string;
    projectId: string;
    scope: {
      [key: string]: string;
    };
    name: string;
    description: string | null;
    currentDeploymentId: string | null;
    createdAt: string;
    updatedAt: string;
    currentDeployment: {
      id: string;
      publicId: string;
      appId: string;
      status: "uploading" | "deploying" | "verifying" | "published";
      clientEntryFileId: string | null;
      logoLightFileId: string | null;
      logoDarkFileId: string | null;
      logoLightPath: string | null;
      logoDarkPath: string | null;
      createdAt: string;
      updatedAt: string;
    } | null;
    clientPath?: string;
    logoPaths?: {
      dark?: string;
      light?: string;
    };
  };
};

export type AppsCreateResponse = AppsCreateResponses[keyof AppsCreateResponses];

export type AppsDeleteData = {
  body?: never;
  path: {
    appId: string;
  };
  query: {
    scope: {
      [key: string]: string;
    };
  };
  url: "/apps/{appId}";
};

export type AppsDeleteResponses = {
  /**
   * OK
   */
  200: {
    id: string;
  };
};

export type AppsDeleteResponse = AppsDeleteResponses[keyof AppsDeleteResponses];

export type AppsGetData = {
  body?: never;
  path: {
    appId: string;
  };
  query: {
    scope: {
      [key: string]: string;
    };
  };
  url: "/apps/{appId}";
};

export type AppsGetResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    publicId: string;
    projectId: string;
    scope: {
      [key: string]: string;
    };
    name: string;
    description: string | null;
    currentDeploymentId: string | null;
    createdAt: string;
    updatedAt: string;
    currentDeployment: {
      id: string;
      publicId: string;
      appId: string;
      status: "uploading" | "deploying" | "verifying" | "published";
      clientEntryFileId: string | null;
      logoLightFileId: string | null;
      logoDarkFileId: string | null;
      logoLightPath: string | null;
      logoDarkPath: string | null;
      createdAt: string;
      updatedAt: string;
    } | null;
    clientPath?: string;
    logoPaths?: {
      dark?: string;
      light?: string;
    };
  };
};

export type AppsGetResponse = AppsGetResponses[keyof AppsGetResponses];

export type AppsUpdateData = {
  body: {
    name: string;
    description: string | null;
  };
  path: {
    appId: string;
  };
  query: {
    scope: {
      [key: string]: string;
    };
  };
  url: "/apps/{appId}";
};

export type AppsUpdateResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    publicId: string;
    projectId: string;
    scope: {
      [key: string]: string;
    };
    name: string;
    description: string | null;
    currentDeploymentId: string | null;
    createdAt: string;
    updatedAt: string;
    currentDeployment: {
      id: string;
      publicId: string;
      appId: string;
      status: "uploading" | "deploying" | "verifying" | "published";
      clientEntryFileId: string | null;
      logoLightFileId: string | null;
      logoDarkFileId: string | null;
      logoLightPath: string | null;
      logoDarkPath: string | null;
      createdAt: string;
      updatedAt: string;
    } | null;
    clientPath?: string;
    logoPaths?: {
      dark?: string;
      light?: string;
    };
  };
};

export type AppsUpdateResponse = AppsUpdateResponses[keyof AppsUpdateResponses];

export type AppsDeployData = {
  body: {
    deploymentId: string;
  };
  path: {
    appId: string;
  };
  query: {
    scope: {
      [key: string]: string;
    };
  };
  url: "/apps/{appId}/deploy";
};

export type AppsDeployResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    publicId: string;
    projectId: string;
    scope: {
      [key: string]: string;
    };
    name: string;
    description: string | null;
    currentDeploymentId: string | null;
    createdAt: string;
    updatedAt: string;
    currentDeployment: {
      id: string;
      publicId: string;
      appId: string;
      status: "uploading" | "deploying" | "verifying" | "published";
      clientEntryFileId: string | null;
      logoLightFileId: string | null;
      logoDarkFileId: string | null;
      logoLightPath: string | null;
      logoDarkPath: string | null;
      createdAt: string;
      updatedAt: string;
    } | null;
    clientPath?: string;
    logoPaths?: {
      dark?: string;
      light?: string;
    };
  };
};

export type AppsDeployResponse = AppsDeployResponses[keyof AppsDeployResponses];

export type CliAuthApproveData = {
  body: {
    scope: {
      [key: string]: string;
    };
    userCode: string;
  };
  path?: never;
  query?: never;
  url: "/cli-auth/approve";
};

export type CliAuthApproveResponses = {
  /**
   * OK
   */
  200: {
    id: string;
  };
};

export type CliAuthApproveResponse = CliAuthApproveResponses[keyof CliAuthApproveResponses];

export type CliAuthDenyData = {
  body: {
    userCode: string;
  };
  path?: never;
  query?: never;
  url: "/cli-auth/deny";
};

export type CliAuthDenyResponses = {
  /**
   * OK
   */
  200: {
    id: string;
  };
};

export type CliAuthDenyResponse = CliAuthDenyResponses[keyof CliAuthDenyResponses];

export type CliAuthPollData = {
  body: {
    deviceCode: string;
  };
  path?: never;
  query?: never;
  url: "/cli-auth/poll";
};

export type CliAuthPollResponses = {
  /**
   * OK
   */
  200:
    | {
        status: "pending";
      }
    | {
        status: "denied";
      }
    | {
        deployToken: string;
        scope: {
          [key: string]: string;
        };
        status: "approved";
      }
    | {
        status: "expired";
      };
};

export type CliAuthPollResponse = CliAuthPollResponses[keyof CliAuthPollResponses];

export type CliAuthStartData = {
  body: {
    [key: string]: unknown;
  };
  path?: never;
  query?: never;
  url: "/cli-auth/start";
};

export type CliAuthStartResponses = {
  /**
   * OK
   */
  200: {
    deviceCode: string;
    expiresAt: string;
    userCode: string;
  };
};

export type CliAuthStartResponse = CliAuthStartResponses[keyof CliAuthStartResponses];

export type CliAuthVerifyTokenData = {
  body: {
    deployToken: string;
  };
  path?: never;
  query?: never;
  url: "/cli-auth/verify-token";
};

export type CliAuthVerifyTokenResponses = {
  /**
   * OK
   */
  200: {
    scope: {
      [key: string]: string;
    };
  };
};

export type CliAuthVerifyTokenResponse =
  CliAuthVerifyTokenResponses[keyof CliAuthVerifyTokenResponses];

export type DeploymentsListData = {
  body?: never;
  path?: never;
  query: {
    page?: number;
    pageSize?: number;
    appId: string;
    scope: {
      [key: string]: string;
    };
  };
  url: "/deployments";
};

export type DeploymentsListResponses = {
  /**
   * OK
   */
  200: {
    items: Array<{
      id: string;
      publicId: string;
      appId: string;
      status: "uploading" | "deploying" | "verifying" | "published";
      clientEntryFileId: string | null;
      logoLightFileId: string | null;
      logoDarkFileId: string | null;
      logoLightPath: string | null;
      logoDarkPath: string | null;
      createdAt: string;
      updatedAt: string;
    }>;
    pagination: {
      hasMore: boolean;
      page: number;
      pageSize: number;
    };
  };
};

export type DeploymentsListResponse = DeploymentsListResponses[keyof DeploymentsListResponses];

export type DeploymentsCreateData = {
  body: {
    appId: string;
    assets: [
      {
        checksum: string;
        contentLength: number;
        contentType: "application/javascript";
        encoding: "utf-8";
        objectKey: "client.js";
      },
    ];
    logos?: {
      dark?: {
        checksum: string;
        contentLength: number;
        contentType: "image/svg+xml" | "image/png" | "image/webp";
      };
      light?: {
        checksum: string;
        contentLength: number;
        contentType: "image/svg+xml" | "image/png" | "image/webp";
      };
    };
    scope: {
      [key: string]: string;
    };
  };
  path?: never;
  query?: never;
  url: "/deployments";
};

export type DeploymentsCreateResponses = {
  /**
   * OK
   */
  200: {
    assets: Array<{
      file: {
        id: string;
        appDeploymentId: string;
        objectKey: string;
        contentType: "application/javascript" | "image/svg+xml" | "image/png" | "image/webp";
        encoding: "utf-8" | null;
        contentLength: number;
        checksum: string | null;
        status: "uploading" | "verifying" | "verified" | "failed";
        createdAt: string;
        updatedAt: string;
      };
      headers?: {
        [key: string]: string;
      };
      uploadUrl: string;
    }>;
    deployment: {
      id: string;
      publicId: string;
      appId: string;
      status: "uploading" | "deploying" | "verifying" | "published";
      clientEntryFileId: string | null;
      logoLightFileId: string | null;
      logoDarkFileId: string | null;
      logoLightPath: string | null;
      logoDarkPath: string | null;
      createdAt: string;
      updatedAt: string;
    };
    logos?: {
      dark?: {
        file: {
          id: string;
          appDeploymentId: string;
          objectKey: string;
          contentType: "image/svg+xml" | "image/png" | "image/webp";
          encoding: "utf-8" | null;
          contentLength: number;
          checksum: string | null;
          status: "uploading" | "verifying" | "verified" | "failed";
          createdAt: string;
          updatedAt: string;
        };
        headers?: {
          [key: string]: string;
        };
        uploadUrl?: string;
      };
      light?: {
        file: {
          id: string;
          appDeploymentId: string;
          objectKey: string;
          contentType: "image/svg+xml" | "image/png" | "image/webp";
          encoding: "utf-8" | null;
          contentLength: number;
          checksum: string | null;
          status: "uploading" | "verifying" | "verified" | "failed";
          createdAt: string;
          updatedAt: string;
        };
        headers?: {
          [key: string]: string;
        };
        uploadUrl?: string;
      };
    };
  };
};

export type DeploymentsCreateResponse =
  DeploymentsCreateResponses[keyof DeploymentsCreateResponses];

export type DeploymentsGetData = {
  body?: never;
  path: {
    deploymentId: string;
  };
  query: {
    scope: {
      [key: string]: string;
    };
  };
  url: "/deployments/{deploymentId}";
};

export type DeploymentsGetResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    publicId: string;
    appId: string;
    status: "uploading" | "deploying" | "verifying" | "published";
    clientEntryFileId: string | null;
    logoLightFileId: string | null;
    logoDarkFileId: string | null;
    logoLightPath: string | null;
    logoDarkPath: string | null;
    createdAt: string;
    updatedAt: string;
  };
};

export type DeploymentsGetResponse = DeploymentsGetResponses[keyof DeploymentsGetResponses];

export type DeploymentsPublishData = {
  body: {
    scope: {
      [key: string]: string;
    };
    rollout?: boolean;
  };
  path: {
    deploymentId: string;
  };
  query?: never;
  url: "/deployments/{deploymentId}";
};

export type DeploymentsPublishResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    publicId: string;
    appId: string;
    status: "uploading" | "deploying" | "verifying" | "published";
    clientEntryFileId: string | null;
    logoLightFileId: string | null;
    logoDarkFileId: string | null;
    logoLightPath: string | null;
    logoDarkPath: string | null;
    createdAt: string;
    updatedAt: string;
  };
};

export type DeploymentsPublishResponse =
  DeploymentsPublishResponses[keyof DeploymentsPublishResponses];

export type PreviewStartData = {
  body: {
    appId: string;
    deployToken: string;
    replaceActive?: boolean;
  };
  path?: never;
  query?: never;
  url: "/preview/start";
};

export type PreviewStartResponses = {
  /**
   * OK
   */
  200: {
    expiresAt: string;
    sessionId: string;
    tunnelToken: string;
    tunnelUrl: string;
    shareId: string;
  };
};

export type PreviewStartResponse = PreviewStartResponses[keyof PreviewStartResponses];

export type PreviewStopData = {
  body: {
    deployToken: string;
  };
  path: {
    sessionId: string;
  };
  query?: never;
  url: "/preview/{sessionId}/stop";
};

export type PreviewStopResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: unknown;
  };
};

export type PreviewStopResponse = PreviewStopResponses[keyof PreviewStopResponses];

export type PreviewInvitationData = {
  body?: never;
  path: {
    shareId: string;
  };
  query?: never;
  url: "/preview/shares/{shareId}";
};

export type PreviewInvitationResponses = {
  /**
   * OK
   */
  200: {
    appName: string;
    expiresAt: string;
    sessionId: string;
  };
};

export type PreviewInvitationResponse =
  PreviewInvitationResponses[keyof PreviewInvitationResponses];

export type PreviewAcceptData = {
  body: {
    scope: {
      [key: string]: string;
    };
  };
  path: {
    shareId: string;
  };
  query?: never;
  url: "/preview/shares/{shareId}/accept";
};

export type PreviewAcceptResponses = {
  /**
   * OK
   */
  200: {
    grantId: string;
    sessionId: string;
  };
};

export type PreviewAcceptResponse = PreviewAcceptResponses[keyof PreviewAcceptResponses];

export type PreviewAcceptedData = {
  body: {
    grantIds: Array<string>;
    scope: {
      [key: string]: string;
    };
  };
  path?: never;
  query?: never;
  url: "/preview/grants/resolve";
};

export type PreviewAcceptedResponses = {
  /**
   * OK
   */
  200: {
    items: Array<{
      app: {
        id: string;
        publicId: string;
        projectId: string;
        scope: {
          [key: string]: string;
        };
        name: string;
        description: string | null;
        currentDeploymentId: string | null;
        createdAt: string;
        updatedAt: string;
        currentDeployment: {
          id: string;
          publicId: string;
          appId: string;
          status: "uploading" | "deploying" | "verifying" | "published";
          clientEntryFileId: string | null;
          logoLightFileId: string | null;
          logoDarkFileId: string | null;
          logoLightPath: string | null;
          logoDarkPath: string | null;
          createdAt: string;
          updatedAt: string;
        } | null;
        clientPath?: string;
        logoPaths?: {
          dark?: string;
          light?: string;
        };
      };
      preview: {
        sessionId: string;
        expiresAt: string;
        websocketUrl: string;
        token: string;
      };
    }>;
  };
};

export type PreviewAcceptedResponse = PreviewAcceptedResponses[keyof PreviewAcceptedResponses];
