// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://tailorkit.dev/api/platform" | (string & {});
};

export type Schema0 =
  | string
  | number
  | boolean
  | null
  | Array<Schema0>
  | {
      [key: string]: Schema0;
    };

export type CliVerifyData = {
  body: {
    [key: string]: never;
  };
  path?: never;
  query?: never;
  url: "/cli/verify";
};

export type CliVerifyResponses = {
  /**
   * OK
   */
  200: {
    projectId: string;
    scope: {
      name: string;
      value: {
        [key: string]: Schema0;
      };
    };
  };
};

export type CliVerifyResponse = CliVerifyResponses[keyof CliVerifyResponses];

export type CliAppsCreateData = {
  body: {
    name: string;
    description: string | null;
  };
  path?: never;
  query?: never;
  url: "/cli/apps";
};

export type CliAppsCreateResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    publicId: string;
    projectId: string;
    scope: {
      name: string;
      value: {
        [key: string]: Schema0;
      };
    };
    name: string;
    description: string | null;
    currentDeploymentId: string | null;
    createdAt: string;
    updatedAt: string;
    currentDeployment: {
      id: string;
      publicId: string;
      appId: string;
      status: "uploading" | "deploying" | "verifying" | "published";
      clientEntryFileId: string | null;
      logoLightFileId: string | null;
      logoDarkFileId: string | null;
      views: Array<{
        slot: string;
        path: string;
        instances?: true;
        disabled?: true;
      }>;
      logoLightPath: string | null;
      logoDarkPath: string | null;
      createdAt: string;
      updatedAt: string;
    } | null;
    views: Array<{
      slot: string;
      path: string;
      instances?: true;
      disabled?: true;
    }>;
    clientPath?: string;
    logoPaths?: {
      dark?: string;
      light?: string;
    };
  };
};

export type CliAppsCreateResponse = CliAppsCreateResponses[keyof CliAppsCreateResponses];

export type CliDeploymentsCreateData = {
  body: {
    appId: string;
    assets: [
      {
        checksum: string;
        contentLength: number;
        contentType: "application/javascript";
        encoding: "utf-8" | "gzip";
        objectKey: "client.js";
      },
    ];
    server?: {
      checksum: string;
      contentLength: number;
      contentType: "application/javascript";
      encoding: "utf-8" | "gzip";
      objectKey: "server.js";
    };
    logos?: {
      dark?: {
        checksum: string;
        contentLength: number;
        contentType: "image/svg+xml" | "image/png" | "image/webp";
      };
      light?: {
        checksum: string;
        contentLength: number;
        contentType: "image/svg+xml" | "image/png" | "image/webp";
      };
    };
    views?: Array<{
      slot: string;
      path: string;
      instances?: true;
      disabled?: true;
    }>;
  };
  path?: never;
  query?: never;
  url: "/cli/deployments";
};

export type CliDeploymentsCreateResponses = {
  /**
   * OK
   */
  200: {
    assets: Array<{
      file: {
        id: string;
        appDeploymentId: string;
        objectKey: string;
        contentType: "application/javascript" | "image/svg+xml" | "image/png" | "image/webp";
        encoding: "utf-8" | "gzip" | null;
        contentLength: number;
        checksum: string | null;
        status: "uploading" | "verifying" | "verified" | "failed";
        createdAt: string;
        updatedAt: string;
      };
      headers?: {
        [key: string]: string;
      };
      uploadUrl: string;
    }>;
    server?: {
      file: {
        id: string;
        appDeploymentId: string;
        objectKey: string;
        contentType: "application/javascript" | "image/svg+xml" | "image/png" | "image/webp";
        encoding: "utf-8" | "gzip" | null;
        contentLength: number;
        checksum: string | null;
        status: "uploading" | "verifying" | "verified" | "failed";
        createdAt: string;
        updatedAt: string;
      };
      headers?: {
        [key: string]: string;
      };
      uploadUrl: string;
    };
    deployment: {
      id: string;
      publicId: string;
      appId: string;
      status: "uploading" | "deploying" | "verifying" | "published";
      clientEntryFileId: string | null;
      logoLightFileId: string | null;
      logoDarkFileId: string | null;
      views: Array<{
        slot: string;
        path: string;
        instances?: true;
        disabled?: true;
      }>;
      logoLightPath: string | null;
      logoDarkPath: string | null;
      createdAt: string;
      updatedAt: string;
    };
    logos?: {
      dark?: {
        file: {
          id: string;
          appDeploymentId: string;
          objectKey: string;
          contentType: "image/svg+xml" | "image/png" | "image/webp";
          encoding: "utf-8" | "gzip" | null;
          contentLength: number;
          checksum: string | null;
          status: "uploading" | "verifying" | "verified" | "failed";
          createdAt: string;
          updatedAt: string;
        };
        headers?: {
          [key: string]: string;
        };
        uploadUrl?: string;
      };
      light?: {
        file: {
          id: string;
          appDeploymentId: string;
          objectKey: string;
          contentType: "image/svg+xml" | "image/png" | "image/webp";
          encoding: "utf-8" | "gzip" | null;
          contentLength: number;
          checksum: string | null;
          status: "uploading" | "verifying" | "verified" | "failed";
          createdAt: string;
          updatedAt: string;
        };
        headers?: {
          [key: string]: string;
        };
        uploadUrl?: string;
      };
    };
  };
};

export type CliDeploymentsCreateResponse =
  CliDeploymentsCreateResponses[keyof CliDeploymentsCreateResponses];

export type CliDeploymentsPublishData = {
  body: {
    rollout?: boolean;
  };
  path: {
    deploymentId: string;
  };
  query?: never;
  url: "/cli/deployments/{deploymentId}";
};

export type CliDeploymentsPublishResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    publicId: string;
    appId: string;
    status: "uploading" | "deploying" | "verifying" | "published";
    clientEntryFileId: string | null;
    logoLightFileId: string | null;
    logoDarkFileId: string | null;
    views: Array<{
      slot: string;
      path: string;
      instances?: true;
      disabled?: true;
    }>;
    logoLightPath: string | null;
    logoDarkPath: string | null;
    createdAt: string;
    updatedAt: string;
  };
};

export type CliDeploymentsPublishResponse =
  CliDeploymentsPublishResponses[keyof CliDeploymentsPublishResponses];

export type AppAgentChatData = {
  body: {
    appId: string;
    hostUrl: string;
    schema?: {
      [key: string]: unknown;
    };
    messages: Array<{
      id: string;
      role: "user" | "assistant";
      parts: Array<{
        type: string;
        [key: string]: unknown;
      }>;
      metadata?: unknown;
    }>;
    deployToken: string;
  };
  path?: never;
  query?: never;
  url: "/app-agent/chat";
};

export type AppAgentChatResponses = {
  /**
   * OK
   */
  200:
    | {
        event: "message";
        /**
         * An AI SDK UIMessageChunk. Fields depend on the chunk type.
         */
        data: unknown;
        id?: string;
        retry?: number;
      }
    | {
        event: "close";
        data?: unknown;
        id?: string;
        retry?: number;
      }
    | {
        event: "error";
        data?: unknown;
        id?: string;
        retry?: number;
      };
};

export type AppAgentChatResponse = AppAgentChatResponses[keyof AppAgentChatResponses];

export type AppsRuntimeSessionData = {
  body: {
    scopes: Array<{
      name: string;
      value: {
        [key: string]: Schema0;
      };
    }>;
    subjectId?: string;
    toolUrl: string;
  };
  path: {
    appId: string;
  };
  query?: never;
  url: "/apps/{appId}/runtime/session";
};

export type AppsRuntimeSessionResponses = {
  /**
   * OK
   */
  200: {
    token: string;
    expiresAt: number;
    url: string;
    toolUrl: string;
    identity: {
      subjectId?: string;
      installationId: string;
      appId: string;
      projectId: string;
      deploymentId: string;
      scope: {
        name: string;
        value: {
          [key: string]: Schema0;
        };
      };
      toolUrl: string;
      expiresAt: number;
    };
  };
};

export type AppsRuntimeSessionResponse =
  AppsRuntimeSessionResponses[keyof AppsRuntimeSessionResponses];

export type AppsListData = {
  body: {
    page?: number;
    pageSize?: number;
    scopes: Array<{
      name: string;
      value: {
        [key: string]: Schema0;
      };
    }>;
  };
  path?: never;
  query?: never;
  url: "/apps/list";
};

export type AppsListResponses = {
  /**
   * OK
   */
  200: {
    items: Array<{
      id: string;
      publicId: string;
      projectId: string;
      scope: {
        name: string;
        value: {
          [key: string]: Schema0;
        };
      };
      name: string;
      description: string | null;
      currentDeploymentId: string | null;
      createdAt: string;
      updatedAt: string;
      currentDeployment: {
        id: string;
        publicId: string;
        appId: string;
        status: "uploading" | "deploying" | "verifying" | "published";
        clientEntryFileId: string | null;
        logoLightFileId: string | null;
        logoDarkFileId: string | null;
        views: Array<{
          slot: string;
          path: string;
          instances?: true;
          disabled?: true;
        }>;
        logoLightPath: string | null;
        logoDarkPath: string | null;
        createdAt: string;
        updatedAt: string;
      } | null;
      views: Array<{
        slot: string;
        path: string;
        instances?: true;
        disabled?: true;
      }>;
      clientPath?: string;
      logoPaths?: {
        dark?: string;
        light?: string;
      };
    }>;
    pagination: {
      hasMore: boolean;
      page: number;
      pageSize: number;
    };
  };
};

export type AppsListResponse = AppsListResponses[keyof AppsListResponses];

export type AppsGetData = {
  body: {
    scopes: Array<{
      name: string;
      value: {
        [key: string]: Schema0;
      };
    }>;
  };
  path: {
    appId: string;
  };
  query?: never;
  url: "/apps/{appId}/lookup";
};

export type AppsGetResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    publicId: string;
    projectId: string;
    scope: {
      name: string;
      value: {
        [key: string]: Schema0;
      };
    };
    name: string;
    description: string | null;
    currentDeploymentId: string | null;
    createdAt: string;
    updatedAt: string;
    currentDeployment: {
      id: string;
      publicId: string;
      appId: string;
      status: "uploading" | "deploying" | "verifying" | "published";
      clientEntryFileId: string | null;
      logoLightFileId: string | null;
      logoDarkFileId: string | null;
      views: Array<{
        slot: string;
        path: string;
        instances?: true;
        disabled?: true;
      }>;
      logoLightPath: string | null;
      logoDarkPath: string | null;
      createdAt: string;
      updatedAt: string;
    } | null;
    views: Array<{
      slot: string;
      path: string;
      instances?: true;
      disabled?: true;
    }>;
    clientPath?: string;
    logoPaths?: {
      dark?: string;
      light?: string;
    };
  };
};

export type AppsGetResponse = AppsGetResponses[keyof AppsGetResponses];

export type AppsCreateData = {
  body: {
    name: string;
    description: string | null;
    scope: {
      name: string;
      value: {
        [key: string]: Schema0;
      };
    };
  };
  path?: never;
  query?: never;
  url: "/apps";
};

export type AppsCreateResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    publicId: string;
    projectId: string;
    scope: {
      name: string;
      value: {
        [key: string]: Schema0;
      };
    };
    name: string;
    description: string | null;
    currentDeploymentId: string | null;
    createdAt: string;
    updatedAt: string;
    currentDeployment: {
      id: string;
      publicId: string;
      appId: string;
      status: "uploading" | "deploying" | "verifying" | "published";
      clientEntryFileId: string | null;
      logoLightFileId: string | null;
      logoDarkFileId: string | null;
      views: Array<{
        slot: string;
        path: string;
        instances?: true;
        disabled?: true;
      }>;
      logoLightPath: string | null;
      logoDarkPath: string | null;
      createdAt: string;
      updatedAt: string;
    } | null;
    views: Array<{
      slot: string;
      path: string;
      instances?: true;
      disabled?: true;
    }>;
    clientPath?: string;
    logoPaths?: {
      dark?: string;
      light?: string;
    };
  };
};

export type AppsCreateResponse = AppsCreateResponses[keyof AppsCreateResponses];

export type AppsDeleteData = {
  body: {
    scope: {
      name: string;
      value: {
        [key: string]: Schema0;
      };
    };
  };
  path: {
    appId: string;
  };
  query?: never;
  url: "/apps/{appId}";
};

export type AppsDeleteResponses = {
  /**
   * OK
   */
  200: {
    id: string;
  };
};

export type AppsDeleteResponse = AppsDeleteResponses[keyof AppsDeleteResponses];

export type AppsUpdateData = {
  body: {
    name: string;
    description: string | null;
    scope: {
      name: string;
      value: {
        [key: string]: Schema0;
      };
    };
  };
  path: {
    appId: string;
  };
  query?: never;
  url: "/apps/{appId}";
};

export type AppsUpdateResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    publicId: string;
    projectId: string;
    scope: {
      name: string;
      value: {
        [key: string]: Schema0;
      };
    };
    name: string;
    description: string | null;
    currentDeploymentId: string | null;
    createdAt: string;
    updatedAt: string;
    currentDeployment: {
      id: string;
      publicId: string;
      appId: string;
      status: "uploading" | "deploying" | "verifying" | "published";
      clientEntryFileId: string | null;
      logoLightFileId: string | null;
      logoDarkFileId: string | null;
      views: Array<{
        slot: string;
        path: string;
        instances?: true;
        disabled?: true;
      }>;
      logoLightPath: string | null;
      logoDarkPath: string | null;
      createdAt: string;
      updatedAt: string;
    } | null;
    views: Array<{
      slot: string;
      path: string;
      instances?: true;
      disabled?: true;
    }>;
    clientPath?: string;
    logoPaths?: {
      dark?: string;
      light?: string;
    };
  };
};

export type AppsUpdateResponse = AppsUpdateResponses[keyof AppsUpdateResponses];

export type AppsDeployData = {
  body: {
    deploymentId: string;
    scope: {
      name: string;
      value: {
        [key: string]: Schema0;
      };
    };
  };
  path: {
    appId: string;
  };
  query?: never;
  url: "/apps/{appId}/deploy";
};

export type AppsDeployResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    publicId: string;
    projectId: string;
    scope: {
      name: string;
      value: {
        [key: string]: Schema0;
      };
    };
    name: string;
    description: string | null;
    currentDeploymentId: string | null;
    createdAt: string;
    updatedAt: string;
    currentDeployment: {
      id: string;
      publicId: string;
      appId: string;
      status: "uploading" | "deploying" | "verifying" | "published";
      clientEntryFileId: string | null;
      logoLightFileId: string | null;
      logoDarkFileId: string | null;
      views: Array<{
        slot: string;
        path: string;
        instances?: true;
        disabled?: true;
      }>;
      logoLightPath: string | null;
      logoDarkPath: string | null;
      createdAt: string;
      updatedAt: string;
    } | null;
    views: Array<{
      slot: string;
      path: string;
      instances?: true;
      disabled?: true;
    }>;
    clientPath?: string;
    logoPaths?: {
      dark?: string;
      light?: string;
    };
  };
};

export type AppsDeployResponse = AppsDeployResponses[keyof AppsDeployResponses];

export type CliAuthApproveData = {
  body: {
    scope: {
      name: string;
      value: {
        [key: string]: Schema0;
      };
    };
    userCode: string;
  };
  path?: never;
  query?: never;
  url: "/cli-auth/approve";
};

export type CliAuthApproveResponses = {
  /**
   * OK
   */
  200: {
    id: string;
  };
};

export type CliAuthApproveResponse = CliAuthApproveResponses[keyof CliAuthApproveResponses];

export type CliAuthDenyData = {
  body: {
    userCode: string;
  };
  path?: never;
  query?: never;
  url: "/cli-auth/deny";
};

export type CliAuthDenyResponses = {
  /**
   * OK
   */
  200: {
    id: string;
  };
};

export type CliAuthDenyResponse = CliAuthDenyResponses[keyof CliAuthDenyResponses];

export type CliAuthPollData = {
  body: {
    deviceCode: string;
  };
  path?: never;
  query?: never;
  url: "/cli-auth/poll";
};

export type CliAuthPollResponses = {
  /**
   * OK
   */
  200:
    | {
        status: "pending";
      }
    | {
        status: "denied";
      }
    | {
        deployToken: string;
        scope: {
          name: string;
          value: {
            [key: string]: Schema0;
          };
        };
        status: "approved";
      }
    | {
        status: "expired";
      };
};

export type CliAuthPollResponse = CliAuthPollResponses[keyof CliAuthPollResponses];

export type CliAuthStartData = {
  body: {
    [key: string]: unknown;
  };
  path?: never;
  query?: never;
  url: "/cli-auth/start";
};

export type CliAuthStartResponses = {
  /**
   * OK
   */
  200: {
    deviceCode: string;
    expiresAt: string;
    userCode: string;
  };
};

export type CliAuthStartResponse = CliAuthStartResponses[keyof CliAuthStartResponses];

export type CliAuthVerifyTokenData = {
  body: {
    deployToken: string;
  };
  path?: never;
  query?: never;
  url: "/cli-auth/verify-token";
};

export type CliAuthVerifyTokenResponses = {
  /**
   * OK
   */
  200: {
    scope: {
      name: string;
      value: {
        [key: string]: Schema0;
      };
    };
  };
};

export type CliAuthVerifyTokenResponse =
  CliAuthVerifyTokenResponses[keyof CliAuthVerifyTokenResponses];

export type DeploymentsListData = {
  body: {
    page?: number;
    pageSize?: number;
    appId: string;
    scopes: Array<{
      name: string;
      value: {
        [key: string]: Schema0;
      };
    }>;
  };
  path?: never;
  query?: never;
  url: "/deployments/list";
};

export type DeploymentsListResponses = {
  /**
   * OK
   */
  200: {
    items: Array<{
      id: string;
      publicId: string;
      appId: string;
      status: "uploading" | "deploying" | "verifying" | "published";
      clientEntryFileId: string | null;
      logoLightFileId: string | null;
      logoDarkFileId: string | null;
      views: Array<{
        slot: string;
        path: string;
        instances?: true;
        disabled?: true;
      }>;
      logoLightPath: string | null;
      logoDarkPath: string | null;
      createdAt: string;
      updatedAt: string;
    }>;
    pagination: {
      hasMore: boolean;
      page: number;
      pageSize: number;
    };
  };
};

export type DeploymentsListResponse = DeploymentsListResponses[keyof DeploymentsListResponses];

export type DeploymentsGetData = {
  body: {
    scopes: Array<{
      name: string;
      value: {
        [key: string]: Schema0;
      };
    }>;
  };
  path: {
    deploymentId: string;
  };
  query?: never;
  url: "/deployments/{deploymentId}/lookup";
};

export type DeploymentsGetResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    publicId: string;
    appId: string;
    status: "uploading" | "deploying" | "verifying" | "published";
    clientEntryFileId: string | null;
    logoLightFileId: string | null;
    logoDarkFileId: string | null;
    views: Array<{
      slot: string;
      path: string;
      instances?: true;
      disabled?: true;
    }>;
    logoLightPath: string | null;
    logoDarkPath: string | null;
    createdAt: string;
    updatedAt: string;
  };
};

export type DeploymentsGetResponse = DeploymentsGetResponses[keyof DeploymentsGetResponses];

export type DeploymentsCreateData = {
  body: {
    appId: string;
    assets: [
      {
        checksum: string;
        contentLength: number;
        contentType: "application/javascript";
        encoding: "utf-8" | "gzip";
        objectKey: "client.js";
      },
    ];
    server?: {
      checksum: string;
      contentLength: number;
      contentType: "application/javascript";
      encoding: "utf-8" | "gzip";
      objectKey: "server.js";
    };
    logos?: {
      dark?: {
        checksum: string;
        contentLength: number;
        contentType: "image/svg+xml" | "image/png" | "image/webp";
      };
      light?: {
        checksum: string;
        contentLength: number;
        contentType: "image/svg+xml" | "image/png" | "image/webp";
      };
    };
    views?: Array<{
      slot: string;
      path: string;
      instances?: true;
      disabled?: true;
    }>;
    scope: {
      name: string;
      value: {
        [key: string]: Schema0;
      };
    };
  };
  path?: never;
  query?: never;
  url: "/deployments";
};

export type DeploymentsCreateResponses = {
  /**
   * OK
   */
  200: {
    assets: Array<{
      file: {
        id: string;
        appDeploymentId: string;
        objectKey: string;
        contentType: "application/javascript" | "image/svg+xml" | "image/png" | "image/webp";
        encoding: "utf-8" | "gzip" | null;
        contentLength: number;
        checksum: string | null;
        status: "uploading" | "verifying" | "verified" | "failed";
        createdAt: string;
        updatedAt: string;
      };
      headers?: {
        [key: string]: string;
      };
      uploadUrl: string;
    }>;
    server?: {
      file: {
        id: string;
        appDeploymentId: string;
        objectKey: string;
        contentType: "application/javascript" | "image/svg+xml" | "image/png" | "image/webp";
        encoding: "utf-8" | "gzip" | null;
        contentLength: number;
        checksum: string | null;
        status: "uploading" | "verifying" | "verified" | "failed";
        createdAt: string;
        updatedAt: string;
      };
      headers?: {
        [key: string]: string;
      };
      uploadUrl: string;
    };
    deployment: {
      id: string;
      publicId: string;
      appId: string;
      status: "uploading" | "deploying" | "verifying" | "published";
      clientEntryFileId: string | null;
      logoLightFileId: string | null;
      logoDarkFileId: string | null;
      views: Array<{
        slot: string;
        path: string;
        instances?: true;
        disabled?: true;
      }>;
      logoLightPath: string | null;
      logoDarkPath: string | null;
      createdAt: string;
      updatedAt: string;
    };
    logos?: {
      dark?: {
        file: {
          id: string;
          appDeploymentId: string;
          objectKey: string;
          contentType: "image/svg+xml" | "image/png" | "image/webp";
          encoding: "utf-8" | "gzip" | null;
          contentLength: number;
          checksum: string | null;
          status: "uploading" | "verifying" | "verified" | "failed";
          createdAt: string;
          updatedAt: string;
        };
        headers?: {
          [key: string]: string;
        };
        uploadUrl?: string;
      };
      light?: {
        file: {
          id: string;
          appDeploymentId: string;
          objectKey: string;
          contentType: "image/svg+xml" | "image/png" | "image/webp";
          encoding: "utf-8" | "gzip" | null;
          contentLength: number;
          checksum: string | null;
          status: "uploading" | "verifying" | "verified" | "failed";
          createdAt: string;
          updatedAt: string;
        };
        headers?: {
          [key: string]: string;
        };
        uploadUrl?: string;
      };
    };
  };
};

export type DeploymentsCreateResponse =
  DeploymentsCreateResponses[keyof DeploymentsCreateResponses];

export type DeploymentsPublishData = {
  body: {
    scope: {
      name: string;
      value: {
        [key: string]: Schema0;
      };
    };
    rollout?: boolean;
  };
  path: {
    deploymentId: string;
  };
  query?: never;
  url: "/deployments/{deploymentId}";
};

export type DeploymentsPublishResponses = {
  /**
   * OK
   */
  200: {
    id: string;
    publicId: string;
    appId: string;
    status: "uploading" | "deploying" | "verifying" | "published";
    clientEntryFileId: string | null;
    logoLightFileId: string | null;
    logoDarkFileId: string | null;
    views: Array<{
      slot: string;
      path: string;
      instances?: true;
      disabled?: true;
    }>;
    logoLightPath: string | null;
    logoDarkPath: string | null;
    createdAt: string;
    updatedAt: string;
  };
};

export type DeploymentsPublishResponse =
  DeploymentsPublishResponses[keyof DeploymentsPublishResponses];

export type DeploymentsRuntimeData = {
  body: {
    [key: string]: unknown;
  };
  path: {
    appId: string;
  };
  query?: never;
  url: "/apps/{appId}/runtime";
};

export type DeploymentsRuntimeResponses = {
  /**
   * OK
   */
  200: {
    projectId: string;
    appId: string;
    deploymentId: string;
    objectKey: string;
    checksum: string;
    contentLength: number;
    contentEncoding?: "gzip";
  };
};

export type DeploymentsRuntimeResponse =
  DeploymentsRuntimeResponses[keyof DeploymentsRuntimeResponses];

export type PreviewStartData = {
  body: {
    appId: string;
    deployToken: string;
    replaceActive?: boolean;
  };
  path?: never;
  query?: never;
  url: "/preview/start";
};

export type PreviewStartResponses = {
  /**
   * OK
   */
  200: {
    expiresAt: string;
    sessionId: string;
    tunnelToken: string;
    tunnelUrl: string;
    shareId: string;
  };
};

export type PreviewStartResponse = PreviewStartResponses[keyof PreviewStartResponses];

export type PreviewStopData = {
  body: {
    deployToken: string;
  };
  path: {
    sessionId: string;
  };
  query?: never;
  url: "/preview/{sessionId}/stop";
};

export type PreviewStopResponses = {
  /**
   * OK
   */
  200: {
    [key: string]: never;
  };
};

export type PreviewStopResponse = PreviewStopResponses[keyof PreviewStopResponses];

export type PreviewInvitationData = {
  body?: never;
  path: {
    shareId: string;
  };
  query?: never;
  url: "/preview/shares/{shareId}";
};

export type PreviewInvitationResponses = {
  /**
   * OK
   */
  200: {
    appName: string;
    expiresAt: string;
    sessionId: string;
  };
};

export type PreviewInvitationResponse =
  PreviewInvitationResponses[keyof PreviewInvitationResponses];

export type PreviewAcceptData = {
  body: {
    scope: {
      name: string;
      value: {
        [key: string]: Schema0;
      };
    };
  };
  path: {
    shareId: string;
  };
  query?: never;
  url: "/preview/shares/{shareId}/accept";
};

export type PreviewAcceptResponses = {
  /**
   * OK
   */
  200: {
    grantId: string;
    sessionId: string;
  };
};

export type PreviewAcceptResponse = PreviewAcceptResponses[keyof PreviewAcceptResponses];

export type PreviewAcceptedData = {
  body: {
    grantIds: Array<string>;
    scopes: Array<{
      name: string;
      value: {
        [key: string]: Schema0;
      };
    }>;
  };
  path?: never;
  query?: never;
  url: "/preview/grants/resolve";
};

export type PreviewAcceptedResponses = {
  /**
   * OK
   */
  200: {
    items: Array<{
      app: {
        id: string;
        publicId: string;
        projectId: string;
        scope: {
          name: string;
          value: {
            [key: string]: Schema0;
          };
        };
        name: string;
        description: string | null;
        currentDeploymentId: string | null;
        createdAt: string;
        updatedAt: string;
        currentDeployment: {
          id: string;
          publicId: string;
          appId: string;
          status: "uploading" | "deploying" | "verifying" | "published";
          clientEntryFileId: string | null;
          logoLightFileId: string | null;
          logoDarkFileId: string | null;
          views: Array<{
            slot: string;
            path: string;
            instances?: true;
            disabled?: true;
          }>;
          logoLightPath: string | null;
          logoDarkPath: string | null;
          createdAt: string;
          updatedAt: string;
        } | null;
        views: Array<{
          slot: string;
          path: string;
          instances?: true;
          disabled?: true;
        }>;
        clientPath?: string;
        logoPaths?: {
          dark?: string;
          light?: string;
        };
      };
      preview: {
        sessionId: string;
        expiresAt: string;
        websocketUrl: string;
        token: string;
      };
    }>;
  };
};

export type PreviewAcceptedResponse = PreviewAcceptedResponses[keyof PreviewAcceptedResponses];
