import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import react from "ultracite/oxlint/react";

export default defineConfig({
  extends: [core, react],
  ignorePatterns: [".agents/skills", ".claude/skills", "routeTree.gen.ts"],
  rules: {
    "no-restricted-properties": [
      "error",
      {
        object: "process",
        property: "env",
        message: "Use this package's #env module and define local values in .env or .env.local.",
      },
    ],
    "ban-types": "warn",
    "button-has-type": "off",
    "callback-return": "off",
    "display-name": "off",
    eqeqeq: "warn",
    "func-style": "off",
    "function-component-definition": "off",
    hooks: "off",
    "hook-use-state": "off",
    "iframe-missing-sandbox": "off",
    "import-style": "off",
    "incompatible-library": "off",
    "jsx-curly-brace-presence": "off",
    "jsx-no-constructed-context-values": "off",
    "jsx-no-target-blank": "off",
    "jsx-pascal-case": "off",
    "no-array-reduce": "off",
    "no-await-in-loop": "off",
    "no-clone-element": "off",
    "no-danger": "off",
    "no-empty-function": "off",
    "no-eq-null": "warn",
    "no-inferrable-types": "off",
    "no-multi-assign": "off",
    "no-negated-condition": "off",
    "no-param-reassign": "off",
    "no-react-children": "off",
    "no-redeclare": "off",
    "no-shadow": "off",
    "no-unescaped-entities": "off",
    "no-use-before-define": "off",
    "no-void": "off",
    "prefer-export-from": "off",
    "prefer-named-capture-group": "off",
    "prefer-number-coercion": "off",
    "prefer-single-call": "off",
    purity: "off",
    refs: "off",
    "rule-suppression": "off",
    "rules-of-hooks": "off",
    "set-state-in-effect": "off",
    "state-in-constructor": "off",
    "method-signature-style": "off",
    todo: "off",
    "prefer-await-to-callbacks": "off",
    "prefer-logical-operator-over-ternary": "off",
    "sort-keys": "off",
    "prefer-destructuring": "off",
    "no-barrel-file": "off",
    "no-inline-comments": "off",
    "no-warning-comments": "warn",
    "avoid-new": "off",
    "no-promise-executor-return": "off",
    "no-named-as-default": "off",
    "prefer-ternary": "off",
    "prefer-await-to-then": "off",
    "no-plusplus": "off",
    "unicorn/no-negated-condition": "off",
    "unicorn/prefer-dom-node-dataset": "off",
    "unicorn/no-array-for-each": "off",
    "unicorn/consistent-function-scoping": "off",
  },
  overrides: [
    {
      files: ["packages/env/src/index.ts"],
      rules: {
        "no-restricted-properties": "off",
      },
    },
  ],
});
