/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DocsRouteRouteImport } from "./routes/docs/route";
import { Route as HomeRouteImport } from "./routes/home";
import { Route as LlmsFullDottxtRouteImport } from "./routes/llms-full[.]txt";
import { Route as LlmsDottxtRouteImport } from "./routes/llms[.]txt";
import { Route as ApiSearchRouteImport } from "./routes/api/search";
import { Route as DocsSplatRouteImport } from "./routes/docs/$";
import { Route as LlmsDotmdxDocsSplatRouteImport } from "./routes/llms[.]mdx.docs.$";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: "/docs",
  path: "/docs",
  getParentRoute: () => rootRouteImport,
} as any);
const HomeRoute = HomeRouteImport.update({
  id: "/home",
  path: "/home",
  getParentRoute: () => rootRouteImport,
} as any);
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: "/llms-full.txt",
  path: "/llms-full.txt",
  getParentRoute: () => rootRouteImport,
} as any);
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: "/llms.txt",
  path: "/llms.txt",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: "/api/search",
  path: "/api/search",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => DocsRouteRoute,
} as any);
const LlmsDotmdxDocsSplatRoute = LlmsDotmdxDocsSplatRouteImport.update({
  id: "/llms.mdx/docs/$",
  path: "/llms.mdx/docs/$",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/docs": typeof DocsRouteRouteWithChildren;
  "/home": typeof HomeRoute;
  "/llms-full.txt": typeof LlmsFullDottxtRoute;
  "/llms.txt": typeof LlmsDottxtRoute;
  "/api/search": typeof ApiSearchRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/llms.mdx/docs/$": typeof LlmsDotmdxDocsSplatRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/docs": typeof DocsRouteRouteWithChildren;
  "/home": typeof HomeRoute;
  "/llms-full.txt": typeof LlmsFullDottxtRoute;
  "/llms.txt": typeof LlmsDottxtRoute;
  "/api/search": typeof ApiSearchRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/llms.mdx/docs/$": typeof LlmsDotmdxDocsSplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/docs": typeof DocsRouteRouteWithChildren;
  "/home": typeof HomeRoute;
  "/llms-full.txt": typeof LlmsFullDottxtRoute;
  "/llms.txt": typeof LlmsDottxtRoute;
  "/api/search": typeof ApiSearchRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/llms.mdx/docs/$": typeof LlmsDotmdxDocsSplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/docs"
    | "/home"
    | "/llms-full.txt"
    | "/llms.txt"
    | "/api/search"
    | "/docs/$"
    | "/llms.mdx/docs/$";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/docs"
    | "/home"
    | "/llms-full.txt"
    | "/llms.txt"
    | "/api/search"
    | "/docs/$"
    | "/llms.mdx/docs/$";
  id:
    | "__root__"
    | "/"
    | "/docs"
    | "/home"
    | "/llms-full.txt"
    | "/llms.txt"
    | "/api/search"
    | "/docs/$"
    | "/llms.mdx/docs/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DocsRouteRoute: typeof DocsRouteRouteWithChildren;
  HomeRoute: typeof HomeRoute;
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute;
  LlmsDottxtRoute: typeof LlmsDottxtRoute;
  ApiSearchRoute: typeof ApiSearchRoute;
  LlmsDotmdxDocsSplatRoute: typeof LlmsDotmdxDocsSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs": {
      id: "/docs";
      path: "/docs";
      fullPath: "/docs";
      preLoaderRoute: typeof DocsRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/home": {
      id: "/home";
      path: "/home";
      fullPath: "/home";
      preLoaderRoute: typeof HomeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/llms-full.txt": {
      id: "/llms-full.txt";
      path: "/llms-full.txt";
      fullPath: "/llms-full.txt";
      preLoaderRoute: typeof LlmsFullDottxtRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/llms.txt": {
      id: "/llms.txt";
      path: "/llms.txt";
      fullPath: "/llms.txt";
      preLoaderRoute: typeof LlmsDottxtRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/search": {
      id: "/api/search";
      path: "/api/search";
      fullPath: "/api/search";
      preLoaderRoute: typeof ApiSearchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs/$": {
      id: "/docs/$";
      path: "/$";
      fullPath: "/docs/$";
      preLoaderRoute: typeof DocsSplatRouteImport;
      parentRoute: typeof DocsRouteRoute;
    };
    "/llms.mdx/docs/$": {
      id: "/llms.mdx/docs/$";
      path: "/llms.mdx/docs/$";
      fullPath: "/llms.mdx/docs/$";
      preLoaderRoute: typeof LlmsDotmdxDocsSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface DocsRouteRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute;
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
};

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(DocsRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  HomeRoute: HomeRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ApiSearchRoute: ApiSearchRoute,
  LlmsDotmdxDocsSplatRoute: LlmsDotmdxDocsSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
