import { mkdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { isViewAncestor } from "@tailorkit/core/views";

import { loadTailorKitConfig } from "@tailorkit/app/config/loader";
import { SerializedComponent as SerializedComponentSchema } from "@tailorkit/core/spec";

interface JsonSchema {
  additionalProperties?: boolean | JsonSchema;
  anyOf?: JsonSchema[];
  oneOf?: JsonSchema[];
  allOf?: JsonSchema[];
  const?: unknown;
  enum?: unknown[];
  items?: boolean | JsonSchema;
  prefixItems?: JsonSchema[];
  minItems?: number;
  not?: JsonSchema;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  type?: string | string[];
}

interface SerializedCallback {
  input?: JsonSchema;
  output?: JsonSchema;
}

interface SerializedComponent {
  callbacks?: Record<string, SerializedCallback>;
  fieldKeys?: string[];
  fields?: JsonSchema;
  children?: boolean;
}

interface SerializedView {
  contextOptional?: boolean;
  context?: JsonSchema;
}

interface SerializedTools {
  [key: string]: SerializedTool | SerializedTools;
}

interface SerializedTool {
  kind: "client" | "server";
  input?: JsonSchema;
  output?: JsonSchema;
}

export interface TailorKitSchemaFile {
  tools?: SerializedTools;
  components?: Record<string, SerializedComponent>;
  views?: Record<string, SerializedView>;
  slots?: Record<string, { views: readonly string[]; multiple?: boolean }>;
}

export interface GenerateTypesOptions {
  configPath?: string;
  schema?: TailorKitSchemaFile;
  cwd?: string;
  outFile?: string;
}

const generatedHeader = `/* eslint-disable */

// This file was automatically generated by TailorKit.
// Documentation: https://tailorkit.dev/docs

// Do not make changes to this file directly, as it will be overwritten.
// Exclude this file from linting and formatting to avoid checking generated code.

import { createRemoteComponent } from "tailorkit/client";
`;

const fallbackObjectType = "Record<string, never>";
const primitiveComponentNames = new Set(["Box", "Flex", "Grid", "Inline"]);

const quote = (value: string): string => JSON.stringify(value);

const toPropertyKey = (value: string): string => {
  if (/^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(value)) {
    return value;
  }

  return quote(value);
};

const toLiteralType = (value: unknown): string => {
  if (typeof value === "string") {
    return quote(value);
  }
  if (typeof value === "number" || typeof value === "boolean" || value === null) {
    return JSON.stringify(value);
  }

  return "unknown";
};

const toTypeScriptType = (schema: JsonSchema | undefined, depth = 0): string => {
  if (schema === undefined) {
    return "unknown";
  }

  if (isNeverSchema(schema)) {
    return "never";
  }

  if (schema.const !== undefined) {
    return toLiteralType(schema.const);
  }

  if (schema.enum !== undefined && schema.enum.length > 0) {
    return schema.enum.map(toLiteralType).join(" | ");
  }

  if (schema.allOf !== undefined && schema.allOf.length > 0) {
    const options = schema.allOf.map((option) => toTypeScriptType(option, depth));
    return [...new Set(options)]
      .map((option) => (option.includes(" | ") ? `(${option})` : option))
      .join(" & ");
  }

  const union = schema.anyOf ?? schema.oneOf;
  if (union !== undefined && union.length > 0) {
    const options = union
      .filter((option) => !isNeverSchema(option))
      .map((option) => toTypeScriptType(option, depth))
      .filter((option) => option !== "never");

    if (options.length === 0) {
      return "never";
    }

    const uniqueOptions = [...new Set(options)];
    return uniqueOptions.join(" | ");
  }

  if (Array.isArray(schema.type)) {
    const options = schema.type.map((type) => toTypeScriptType({ ...schema, type }, depth));
    return [...new Set(options)].join(" | ") || "never";
  }

  const schemaType = schema.type;

  if (schemaType === "null") {
    return "null";
  }
  if (schemaType === "string") {
    return "string";
  }
  if (schemaType === "number" || schemaType === "integer") {
    return "number";
  }
  if (schemaType === "boolean") {
    return "boolean";
  }
  if (schemaType === "array") {
    const items = typeof schema.items === "object" ? schema.items : undefined;
    if (schema.prefixItems !== undefined) {
      const tupleItems = schema.prefixItems.map((item, index) => {
        const type = toTypeScriptType(item, depth);
        return index < (schema.minItems ?? 0) ? type : `(${type})?`;
      });
      const additionalRequired = (schema.minItems ?? 0) - schema.prefixItems.length;
      if (additionalRequired > 0 && schema.items === false) {
        return "never";
      }
      for (let index = 0; index < additionalRequired; index += 1) {
        tupleItems.push(toTypeScriptType(items, depth));
      }
      if (schema.items !== false) {
        tupleItems.push(`...${toArrayType(toTypeScriptType(items, depth))}`);
      }
      return `[${tupleItems.join(", ")}]`;
    }
    return toArrayType(schema.items === false ? "never" : toTypeScriptType(items, depth));
  }
  if (schemaType === "object") {
    return toObjectType(schema, depth);
  }

  return "unknown";
};

const toArrayType = (itemType: string): string =>
  `${itemType.includes(" | ") || itemType.includes(" & ") ? `(${itemType})` : itemType}[]`;

const isNeverSchema = (schema: JsonSchema): boolean =>
  schema.not !== undefined && Object.keys(schema.not).length === 0;

const isNeverOnlyObject = (schema: JsonSchema): boolean => {
  const properties = schema.properties ?? {};
  const propertyEntries = Object.values(properties);

  return (
    (Array.isArray(schema.type) ? schema.type.includes("object") : schema.type === "object") &&
    propertyEntries.length > 0 &&
    propertyEntries.every(isNeverSchema)
  );
};

const toObjectType = (schema: JsonSchema, depth: number): string => {
  const properties = schema.properties ?? {};
  const propertyEntries = Object.entries(properties);

  if (isNeverOnlyObject(schema)) {
    return "never";
  }

  const required = new Set(schema.required);
  const catchallType = toTypeScriptType(
    schema.additionalProperties === true ? undefined : schema.additionalProperties || undefined,
    depth,
  );
  const additionalValueTypes = [catchallType];
  if (catchallType !== "unknown") {
    for (const [key, propertySchema] of propertyEntries) {
      additionalValueTypes.push(toTypeScriptType(propertySchema, depth));
      if (!required.has(key)) {
        additionalValueTypes.push("undefined");
      }
    }
  }
  const additionalType =
    schema.additionalProperties === false || schema.additionalProperties === undefined
      ? undefined
      : `Record<string, ${[...new Set(additionalValueTypes)].join(" | ")}>`;

  if (propertyEntries.length === 0) {
    return additionalType ?? fallbackObjectType;
  }

  const currentIndent = " ".repeat(depth);
  const propertyIndent = " ".repeat(depth + 2);
  const lines = ["{"];

  for (const [key, propertySchema] of propertyEntries) {
    const optional = required.has(key) ? "" : "?";
    lines.push(
      `${propertyIndent}${toPropertyKey(key)}${optional}: ${toTypeScriptType(propertySchema, depth + 2)};`,
    );
  }

  lines.push(`${currentIndent}}`);
  const objectType = lines.join("\n");
  return additionalType === undefined ? objectType : `${objectType} & ${additionalType}`;
};

const toIdentifier = (name: string): string => {
  const identifier = name.replaceAll(/[^A-Za-z0-9_$]/gu, "_");

  if (/^[A-Za-z_$]/u.test(identifier)) {
    return identifier;
  }

  return `_${identifier}`;
};

const toPropsName = (componentName: string): string => `${toIdentifier(componentName)}Props`;

const toTypeName = (name: string): string => {
  const identifier = toIdentifier(name);
  return `${identifier.charAt(0).toUpperCase()}${identifier.slice(1)}`;
};

const getComponentFields = (component: SerializedComponent): Record<string, JsonSchema> => {
  if (component.fields?.properties !== undefined) {
    return component.fields.properties;
  }

  const fields: Record<string, JsonSchema> = {};

  for (const key of component.fieldKeys ?? []) {
    fields[key] = {};
  }

  return fields;
};

const renderResponsiveType = (
  schema: JsonSchema | undefined,
  depth: number,
): string | undefined => {
  if (schema?.anyOf === undefined || schema.anyOf.length !== 2) {
    return undefined;
  }

  const [firstOption, secondOption] = schema.anyOf.filter((option) => !isNeverSchema(option));
  if (firstOption === undefined || secondOption === undefined) {
    return undefined;
  }

  let scalarOption: JsonSchema | undefined;
  let responsiveOption: JsonSchema | undefined;

  if (firstOption.type === "object") {
    scalarOption = secondOption;
    responsiveOption = firstOption;
  } else if (secondOption.type === "object") {
    scalarOption = firstOption;
    responsiveOption = secondOption;
  }

  if (scalarOption === undefined || responsiveOption === undefined) {
    return undefined;
  }

  const scalarType = toTypeScriptType(scalarOption, depth);
  if (scalarType === "never") {
    return "never";
  }

  const properties = Object.values(responsiveOption.properties ?? {});
  if (properties.length === 0) {
    return undefined;
  }

  const responsiveTypes = properties.map((property) => toTypeScriptType(property, depth));
  if (responsiveTypes.some((type) => type !== scalarType && type !== "never")) {
    return undefined;
  }

  return `Responsive<${scalarType}>`;
};

const renderFieldType = (schema: JsonSchema | undefined, depth: number): string =>
  renderResponsiveType(schema, depth) ?? toTypeScriptType(schema, depth);

const collectFieldTypeAliases = (
  components: Record<string, SerializedComponent>,
): Record<string, string> => {
  const aliases: Record<string, string> = {};
  const seenByAlias = new Map<string, string>();
  const conflictedAliases = new Set<string>();

  for (const [componentName, component] of Object.entries(components)) {
    if (!primitiveComponentNames.has(componentName)) {
      continue;
    }

    for (const [key, schema] of Object.entries(getComponentFields(component))) {
      const alias = toTypeName(key);
      const type = renderFieldType(schema, 0);
      const seenType = seenByAlias.get(alias);

      if (seenType === undefined) {
        seenByAlias.set(alias, type);
        aliases[key] = alias;
        continue;
      }

      if (seenType !== type) {
        conflictedAliases.add(alias);
      }
    }
  }

  return Object.fromEntries(
    Object.entries(aliases).filter(([, alias]) => !conflictedAliases.has(alias)),
  );
};

const renderTypeAliases = (
  components: Record<string, SerializedComponent>,
  aliases: Record<string, string>,
): string => {
  const lines = [
    'export type Breakpoint = "base" | "sm" | "md" | "lg" | "xl" | "2xl";',
    "export type Responsive<TValue> = TValue | Partial<Record<Breakpoint, TValue>>;",
  ];
  const emitted = new Set<string>();

  for (const [componentName, component] of Object.entries(components)) {
    if (!primitiveComponentNames.has(componentName)) {
      continue;
    }

    for (const [key, schema] of Object.entries(getComponentFields(component))) {
      const alias = aliases[key];
      if (alias === undefined || emitted.has(alias)) {
        continue;
      }

      emitted.add(alias);
      lines.push(`export type ${alias} = ${renderFieldType(schema, 0)};`);
    }
  }

  return lines.join("\n");
};

const renderViewProps = (views: Record<string, SerializedView>): string => {
  const lines = ["export interface ViewPropsByPath {"];

  for (const viewPath of Object.keys(views)) {
    const contexts = Object.entries(views)
      .filter(([parent]) => isViewAncestor(parent, viewPath))
      .filter(([, layer]) => layer.context !== undefined)
      .map(([, layer]) => {
        const context = toTypeScriptType(layer.context, 4);
        return layer.contextOptional ? `Partial<${context}>` : context;
      })
      .filter((context) => context !== "Record<string, never>");
    const context =
      contexts.length > 1
        ? contexts.map((context) => `(${context})`).join(" & ")
        : (contexts[0] ?? "Record<string, never>");
    const contextLines = context.split("\n");
    lines.push(`  ${quote(viewPath)}: {`);
    lines.push(`    context: ${contextLines[0]}`);
    for (const line of contextLines.slice(1, -1)) {
      lines.push(line);
    }
    const lastContextLine = contextLines.at(-1);
    if (lastContextLine !== undefined && contextLines.length > 1) {
      lines.push(`${lastContextLine};`);
    } else {
      lines[lines.length - 1] = `${lines.at(-1)};`;
    }
    lines.push("  };");
  }

  lines.push("}");
  return lines.join("\n");
};

const renderComponent = (
  name: string,
  component: SerializedComponent,
  fieldAliases: Record<string, string>,
): string => {
  const propsName = toPropsName(name);
  const fields = getComponentFields(component);
  const callbacks = component.callbacks ?? {};
  const lines = [`export interface ${propsName} {`];

  for (const [key, schema] of Object.entries(fields)) {
    lines.push(`  ${toPropertyKey(key)}?: ${fieldAliases[key] ?? renderFieldType(schema, 2)};`);
  }

  for (const [key, callback] of Object.entries(callbacks)) {
    const parameters =
      callback.input === undefined ? "" : `input: ${toTypeScriptType(callback.input, 2)}`;
    lines.push(`  ${toPropertyKey(key)}?: (${parameters}) => void;`);
  }

  lines.push("}");
  lines.push("");

  const callbackEntries = Object.entries(callbacks).map(
    ([key, callback]) => `${quote(key)}: ${callback.input === undefined ? 0 : 1}`,
  );
  const callbackOptions =
    callbackEntries.length > 0 ? `,\n  callbacks: { ${callbackEntries.join(", ")} }` : "";

  lines.push(
    `export const ${toIdentifier(name)} = /* @__PURE__ */ createRemoteComponent<${propsName}, ${component.children === true}>(${quote(name)}, {`,
  );
  lines.push(`  children: ${component.children === true}${callbackOptions},`);
  lines.push("});");

  return lines.join("\n");
};

const isSerializedTool = (value: SerializedTool | SerializedTools): value is SerializedTool =>
  "kind" in value && (value.kind === "client" || value.kind === "server");

const hasServerTool = (value: SerializedTool | SerializedTools): boolean =>
  isSerializedTool(value) ? value.kind === "server" : Object.values(value).some(hasServerTool);

const renderTools = (tools: SerializedTools, depth = 0, serverOnly = false): string => {
  const indent = " ".repeat(depth);
  const propertyIndent = " ".repeat(depth + 2);
  const lines = ["{"];

  for (const [key, value] of Object.entries(tools)) {
    if (serverOnly && !hasServerTool(value)) continue;
    if (isSerializedTool(value)) {
      if (serverOnly && value.kind !== "server") continue;
      const input = toTypeScriptType(value.input, depth + 2);
      const output = toTypeScriptType(value.output, depth + 2);
      lines.push(
        `${propertyIndent}${toPropertyKey(key)}: (input${value.input ? "" : "?"}: ${value.input ? input : "undefined"}) => Promise<${value.output ? output : "void"}>;`,
      );
    } else {
      const nested = renderTools(value, depth + 2, serverOnly).split("\n");
      lines.push(`${propertyIndent}${toPropertyKey(key)}: ${nested[0]}`);
      lines.push(...nested.slice(1, -1));
      lines.push(`${nested.at(-1)};`);
    }
  }

  lines.push(`${indent}}`);
  return lines.join("\n");
};

const renderToolRuntime = (tools: SerializedTools, pathParts: string[] = []): string => {
  const lines = ["{"];

  for (const [key, value] of Object.entries(tools)) {
    const path = [...pathParts, key];
    if (isSerializedTool(value)) {
      lines.push(
        `  ${toPropertyKey(key)}: (input?: unknown) => callTool(${quote(value.kind)}, ${quote(path.join("."))}, input),`,
      );
    } else {
      const nested = renderToolRuntime(value, path).split("\n");
      lines.push(`  ${toPropertyKey(key)}: ${nested[0]}`);
      lines.push(...nested.slice(1).map((line) => `  ${line}`));
      lines.push(",");
    }
  }

  lines.push("}");
  return lines.join("\n");
};

export const renderGeneratedTypes = (
  schema: TailorKitSchemaFile,
  options: { serverModule?: string } = {},
): string => {
  const toolsType = renderTools(schema.tools ?? {});
  const components = schema.components ?? {};
  const fieldAliases = collectFieldTypeAliases(components);
  const chunks = [
    generatedHeader,
    `import { callTool } from "tailorkit/client";`,
    renderViewProps(schema.views ?? {}),
    `declare module "tailorkit/client" {
  interface TailorKitViews extends ViewPropsByPath {}
  interface TailorKitSlots { ${Object.entries(schema.slots ?? {})
    .map(
      ([name, slot]) =>
        `${quote(name)}: { views: ${slot.views.map(quote).join(" | ") || "never"}; multiple: ${slot.multiple === true} };`,
    )
    .join(" ")} }
}

export type ViewPath = keyof ViewPropsByPath & string;
export type ViewProps<TPath extends ViewPath> = ViewPropsByPath[TPath];
export type TailorKitTools = ${toolsType};
export type TailorKitBackendTools = ${renderTools(schema.tools ?? {}, 0, true)};
declare module "tailorkit/client" { interface TailorKitServerTools extends TailorKitBackendTools {} }
export const tools = ${renderToolRuntime(schema.tools ?? {})} as TailorKitTools;`,
    renderTypeAliases(components, fieldAliases),
  ];

  if (options.serverModule) {
    chunks.splice(
      1,
      0,
      `import { createApi } from "tailorkit/client";\nimport type app from ${quote(options.serverModule)};\ntype AppServerFunctions = typeof app.functions;\ndeclare module "tailorkit/client" {\n  interface TailorKitServerFunctions extends AppServerFunctions {}\n}\n\nexport const api = createApi<typeof app.functions>();`,
    );
  }

  for (const [name, component] of Object.entries(components)) {
    const { children } = SerializedComponentSchema.parse(component);
    chunks.push(renderComponent(name, { ...component, children }, fieldAliases));
  }

  return `${chunks.join("\n\n")}\n`;
};

const joinUrlPath = (baseUrl: string, pathName: string): string => {
  const url = new URL(baseUrl);
  url.pathname = `${url.pathname.replace(/\/$/u, "")}/${pathName.replace(/^\//u, "")}`;
  return url.toString();
};

export const fetchSchemaFromHost = async (host: string): Promise<TailorKitSchemaFile> => {
  const schemaUrl = joinUrlPath(host, "schema");
  const response = await fetch(schemaUrl);

  if (!response.ok) {
    throw new Error(`Unable to fetch TailorKit schema from ${schemaUrl}: ${response.statusText}`);
  }

  return (await response.json()) as TailorKitSchemaFile;
};

export const generateTypes = async (options: GenerateTypesOptions = {}): Promise<string> => {
  const root = path.resolve(options.cwd ?? ".");
  const outPath = path.resolve(root, options.outFile ?? path.join("src", "tailorkit.gen.ts"));
  const loaded = await loadTailorKitConfig(options.configPath, root);
  const schema = options.schema ?? (await fetchSchemaFromHost(loaded.config.host));

  const serverEntry = path.resolve(loaded.root, loaded.config.server?.entry ?? "src/server.ts");
  const serverExists = await stat(serverEntry)
    .then((file) => file.isFile())
    .catch((error: unknown) => {
      const code = (error as NodeJS.ErrnoException).code;
      if (code === "ENOENT" || code === "ENOTDIR") {
        return false;
      }
      throw error;
    });
  let serverModule: string | undefined;
  if (serverExists) {
    const relative = path
      .relative(path.dirname(outPath), serverEntry)
      .replaceAll(path.sep, "/")
      .replace(/\.tsx?$/u, "");
    serverModule = relative.startsWith(".") ? relative : `./${relative}`;
  }
  const output = renderGeneratedTypes(schema, { serverModule });

  await mkdir(path.dirname(outPath), { recursive: true });
  await writeFile(outPath, output, "utf-8");

  return outPath;
};
