import { existsSync } from "node:fs";
import { createRequire } from "node:module";
import { createHash } from "node:crypto";
import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { StoreDefinition } from "./server";
import type { Migration } from "./internal/driver";
/** Private build/CLI integration. Never import from an app's browser entry. */
export function schemaSource(store: StoreDefinition): string {
  const tables = Object.entries(store.schema).map(([name, fields]) => {
    const columns = Object.entries(fields).map(([key, field]) => {
      const factory = { text: "text", number: "real", boolean: "integer", integer: "integer" }[
        field.kind
      ];
      const options = field.kind === "boolean" ? ', { mode: "boolean" }' : "";
      const chain = `${field.nullable ? "" : ".notNull()"}${field.primaryKey ? ".primaryKey()" : ""}${field.unique ? ".unique()" : ""}`;
      return `${JSON.stringify(key)}: ${factory}(${JSON.stringify(key)}${options})${chain}`;
    });
    return `export const table_${name} = sqliteTable(${JSON.stringify(name)}, { ${columns.join(", ")} });`;
  });
  // Metadata schema is shared with the runtime through the same Drizzle mapping.
  return (
    `import { sqliteTable, text, integer, real } from "drizzle-orm/sqlite-core";\n${tables.join("\n")}\n` +
    'export const tk_receipts = sqliteTable("tk_receipts", { key: text().primaryKey(), fingerprint: text().notNull(), result: text().notNull() });\n' +
    'export const tk_state = sqliteTable("tk_state", { key: text().primaryKey(), value: integer().notNull() });\n'
  );
}
export function schemaFingerprint(store: StoreDefinition) {
  // Compare the actual generated Drizzle model, including runtime-owned metadata tables.
  return createHash("sha256").update(schemaSource(store)).digest("hex");
}
export async function writeReferences(file: string, serverEntry: string, store: StoreDefinition) {
  const relative = path
    .relative(path.dirname(file), serverEntry)
    .replaceAll(path.sep, "/")
    .replace(/\.tsx?$/u, "");
  const serverImport = relative.startsWith(".") ? relative : `./${relative}`;
  const functions = Object.entries(
    store.functions as Record<string, { kind: "query" | "mutation" }>,
  ).map(
    ([name, fn]) =>
      `  ${name}: functionReference(${JSON.stringify(name)}, ${JSON.stringify(fn.kind)}, ${store.apiVersion}),`,
  );
  const content = `// Generated by TailorKit. Server imports are type-only.\nimport type store from ${JSON.stringify(serverImport)};\nimport { functionReference } from "@tailorkit/app-storage";\nimport type { References } from "@tailorkit/app-storage";\n\nexport const api: References<typeof store.functions> = {\n${functions.join("\n")}\n};\n`;
  if ((await readFile(file, "utf-8").catch(() => "")) !== content) {
    await writeFile(file, content);
  }
}
export async function readMigrations(directory: string): Promise<Migration[]> {
  const files: { id: string; file: string }[] = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (entry.isDirectory() && /^\d{14}_/u.test(entry.name)) {
      files.push({ id: entry.name, file: path.join(directory, entry.name, "migration.sql") });
    } else if (entry.isFile() && /^\d+_.+\.sql$/u.test(entry.name)) {
      files.push({ id: entry.name, file: path.join(directory, entry.name) });
    }
  }
  return Promise.all(
    files
      .toSorted((a, b) => a.id.localeCompare(b.id))
      .map(async (entry) => {
        const sql = await readFile(entry.file, "utf-8");
        return {
          id: entry.id,
          hash: createHash("sha256").update(sql).digest("hex"),
          statements: sql.split("--> statement-breakpoint"),
        };
      }),
  );
}
export async function assertGeneratedSchema(directory: string, store: StoreDefinition) {
  const fingerprint = await readFile(
    path.join(directory, "tailorkit-schema.sha256"),
    "utf-8",
  ).catch(() => "");
  if (fingerprint.trim() !== schemaFingerprint(store)) {
    throw new Error(
      "Storage schema changed. Run tailorkit storage generate and commit its migrations before building.",
    );
  }
  const migrations = await readMigrations(directory);
  if (!migrations.length) {
    throw new Error("No generated storage migrations");
  }
}
/** CLI binaries are pinned dependencies rather than npx downloads. */
export function storageTool(name: "drizzle-kit" | "wrangler") {
  const require = createRequire(import.meta.url);
  for (const directory of require.resolve.paths(name) ?? []) {
    const binary = path.join(
      directory,
      name,
      name === "drizzle-kit" ? "bin.cjs" : "bin/wrangler.js",
    );
    if (existsSync(binary)) {
      return binary;
    }
  }
  throw new Error(`Missing pinned storage tool: ${name}`);
}
export function storageDrizzleModule() {
  return fileURLToPath(import.meta.resolve("drizzle-orm/sqlite-core"));
}
