// Generated by TailorKit. Server imports are type-only.
import type store from "./server";
import { functionReference } from "@tailorkit/app-storage";
import type { References } from "@tailorkit/app-storage";

export const api: References<typeof store.functions> = {
  list: functionReference("list", "query", 1),
  add: functionReference("add", "mutation", 1),
  toggle: functionReference("toggle", "mutation", 1),
  remove: functionReference("remove", "mutation", 1),
  seed: functionReference("seed", "mutation", 1),
};
