/* eslint-disable */

// This file was automatically generated by TailorKit.
// Documentation: https://tailorkit.dev/docs

// Do not make changes to this file directly, as it will be overwritten.
// Exclude this file from linting and formatting to avoid checking generated code.

import { createApi, createRemoteComponent } from "tailorkit/client";
import type app from "./server";
type AppServerFunctions = typeof app.functions;
declare module "tailorkit/client" {
  interface TailorKitServerFunctions extends AppServerFunctions {}
}

export const api = createApi<typeof app.functions>();

export interface ViewPropsByPath {
  "/": {
    context: Record<string, never>;
  };
}

declare module "tailorkit/client" {
  interface TailorKitViews extends ViewPropsByPath {}
  interface TailorKitSlots {
    page: { views: "/"; multiple: true };
  }
}

export type ViewPath = keyof ViewPropsByPath & string;
export type ViewProps<TPath extends ViewPath> = ViewPropsByPath[TPath];
export type TailorKitActions = {};
export const actions = {} as TailorKitActions;

export type Breakpoint = "base" | "sm" | "md" | "lg" | "xl" | "2xl";
export type Responsive<TValue> = TValue | Partial<Record<Breakpoint, TValue>>;
export type Background = never;
export type Basis = Responsive<
  | "0"
  | "1/2"
  | "1/3"
  | "2/3"
  | "1/4"
  | "2/4"
  | "3/4"
  | "1/5"
  | "2/5"
  | "3/5"
  | "4/5"
  | "1/6"
  | "2/6"
  | "3/6"
  | "4/6"
  | "5/6"
  | "1/12"
  | "2/12"
  | "3/12"
  | "4/12"
  | "5/12"
  | "6/12"
  | "7/12"
  | "8/12"
  | "9/12"
  | "10/12"
  | "11/12"
  | "full"
  | "min"
  | "max"
  | "fit"
>;
export type Border = Responsive<"solid" | "dashed" | "dotted" | "double">;
export type BorderColor = never;
export type Grow = Responsive<"0" | "1">;
export type Height = Responsive<
  | "0"
  | "1/2"
  | "1/3"
  | "2/3"
  | "1/4"
  | "2/4"
  | "3/4"
  | "1/5"
  | "2/5"
  | "3/5"
  | "4/5"
  | "1/6"
  | "2/6"
  | "3/6"
  | "4/6"
  | "5/6"
  | "1/12"
  | "2/12"
  | "3/12"
  | "4/12"
  | "5/12"
  | "6/12"
  | "7/12"
  | "8/12"
  | "9/12"
  | "10/12"
  | "11/12"
  | "full"
  | "min"
  | "max"
  | "fit"
>;
export type Margin = Responsive<"none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl">;
export type MinHeight = Responsive<
  | "0"
  | "1/2"
  | "1/3"
  | "2/3"
  | "1/4"
  | "2/4"
  | "3/4"
  | "1/5"
  | "2/5"
  | "3/5"
  | "4/5"
  | "1/6"
  | "2/6"
  | "3/6"
  | "4/6"
  | "5/6"
  | "1/12"
  | "2/12"
  | "3/12"
  | "4/12"
  | "5/12"
  | "6/12"
  | "7/12"
  | "8/12"
  | "9/12"
  | "10/12"
  | "11/12"
  | "full"
  | "min"
  | "max"
  | "fit"
>;
export type MinWidth = Responsive<
  | "0"
  | "1/2"
  | "1/3"
  | "2/3"
  | "1/4"
  | "2/4"
  | "3/4"
  | "1/5"
  | "2/5"
  | "3/5"
  | "4/5"
  | "1/6"
  | "2/6"
  | "3/6"
  | "4/6"
  | "5/6"
  | "1/12"
  | "2/12"
  | "3/12"
  | "4/12"
  | "5/12"
  | "6/12"
  | "7/12"
  | "8/12"
  | "9/12"
  | "10/12"
  | "11/12"
  | "full"
  | "min"
  | "max"
  | "fit"
>;
export type Overflow = Responsive<"visible" | "hidden" | "clip" | "scroll" | "auto">;
export type OverflowWrap = Responsive<"normal" | "breakWord" | "anywhere">;
export type Padding = Responsive<"none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl">;
export type Radius = Responsive<"none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl">;
export type Shrink = Responsive<"0" | "1">;
export type TextAlign = Responsive<"left" | "right" | "start" | "end" | "center" | "justify">;
export type TextColor = never;
export type TextOverflow = Responsive<"clip" | "ellipsis">;
export type TextTransform = Responsive<"capitalize" | "uppercase" | "lowercase" | "none">;
export type Width = Responsive<
  | "0"
  | "1/2"
  | "1/3"
  | "2/3"
  | "1/4"
  | "2/4"
  | "3/4"
  | "1/5"
  | "2/5"
  | "3/5"
  | "4/5"
  | "1/6"
  | "2/6"
  | "3/6"
  | "4/6"
  | "5/6"
  | "1/12"
  | "2/12"
  | "3/12"
  | "4/12"
  | "5/12"
  | "6/12"
  | "7/12"
  | "8/12"
  | "9/12"
  | "10/12"
  | "11/12"
  | "full"
  | "min"
  | "max"
  | "fit"
>;
export type Align = Responsive<"start" | "center" | "end" | "stretch">;
export type Direction = Responsive<"row" | "column">;
export type Gap = Responsive<"none" | "2xs" | "xs" | "sm" | "md" | "lg" | "xl" | "2xl" | "3xl">;
export type Justify = Responsive<"start" | "center" | "end" | "between">;
export type Wrap = Responsive<"wrap" | "nowrap" | "wrap-reverse">;
export type Columns = Responsive<1 | 2 | 3 | 4 | 6 | 12>;

export interface BoxProps {
  background?: Background;
  basis?: Basis;
  border?: Border;
  borderColor?: BorderColor;
  grow?: Grow;
  height?: Height;
  margin?: Margin;
  minHeight?: MinHeight;
  minWidth?: MinWidth;
  overflow?: Overflow;
  overflowWrap?: OverflowWrap;
  padding?: Padding;
  radius?: Radius;
  shrink?: Shrink;
  textAlign?: TextAlign;
  textColor?: TextColor;
  textOverflow?: TextOverflow;
  textTransform?: TextTransform;
  width?: Width;
}

export const Box = /* @__PURE__ */ createRemoteComponent<BoxProps, true>("Box", {
  children: true,
});

export interface FlexProps {
  background?: Background;
  basis?: Basis;
  border?: Border;
  borderColor?: BorderColor;
  grow?: Grow;
  height?: Height;
  margin?: Margin;
  minHeight?: MinHeight;
  minWidth?: MinWidth;
  overflow?: Overflow;
  overflowWrap?: OverflowWrap;
  padding?: Padding;
  radius?: Radius;
  shrink?: Shrink;
  textAlign?: TextAlign;
  textColor?: TextColor;
  textOverflow?: TextOverflow;
  textTransform?: TextTransform;
  width?: Width;
  align?: Align;
  direction?: Direction;
  gap?: Gap;
  justify?: Justify;
  wrap?: Wrap;
}

export const Flex = /* @__PURE__ */ createRemoteComponent<FlexProps, true>("Flex", {
  children: true,
});

export interface GridProps {
  background?: Background;
  basis?: Basis;
  border?: Border;
  borderColor?: BorderColor;
  grow?: Grow;
  height?: Height;
  margin?: Margin;
  minHeight?: MinHeight;
  minWidth?: MinWidth;
  overflow?: Overflow;
  overflowWrap?: OverflowWrap;
  padding?: Padding;
  radius?: Radius;
  shrink?: Shrink;
  textAlign?: TextAlign;
  textColor?: TextColor;
  textOverflow?: TextOverflow;
  textTransform?: TextTransform;
  width?: Width;
  columns?: Columns;
  gap?: Gap;
}

export const Grid = /* @__PURE__ */ createRemoteComponent<GridProps, true>("Grid", {
  children: true,
});

export interface InlineProps {
  background?: Background;
  borderColor?: BorderColor;
  margin?: Margin;
  overflowWrap?: OverflowWrap;
  padding?: Padding;
  radius?: Radius;
  textAlign?: TextAlign;
  textColor?: TextColor;
  textOverflow?: TextOverflow;
  textTransform?: TextTransform;
}

export const Inline = /* @__PURE__ */ createRemoteComponent<InlineProps, true>("Inline", {
  children: true,
});

export interface ButtonProps {
  variant?: "default" | "secondary";
  onClick?: () => void;
}

export const Button = /* @__PURE__ */ createRemoteComponent<ButtonProps, true>("Button", {
  children: true,
  callbacks: { onClick: 0 },
});
