/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbedPanelRouteImport } from './routes/embed-panel'
import { Route as ApiTailorkitSplatRouteImport } from './routes/api/tailorkit.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedPanelRoute = EmbedPanelRouteImport.update({
  id: '/embed-panel',
  path: '/embed-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTailorkitSplatRoute = ApiTailorkitSplatRouteImport.update({
  id: '/api/tailorkit/$',
  path: '/api/tailorkit/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/embed-panel': typeof EmbedPanelRoute
  '/api/tailorkit/$': typeof ApiTailorkitSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/embed-panel': typeof EmbedPanelRoute
  '/api/tailorkit/$': typeof ApiTailorkitSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/embed-panel': typeof EmbedPanelRoute
  '/api/tailorkit/$': typeof ApiTailorkitSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/embed-panel' | '/api/tailorkit/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/embed-panel' | '/api/tailorkit/$'
  id: '__root__' | '/' | '/embed-panel' | '/api/tailorkit/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmbedPanelRoute: typeof EmbedPanelRoute
  ApiTailorkitSplatRoute: typeof ApiTailorkitSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed-panel': {
      id: '/embed-panel'
      path: '/embed-panel'
      fullPath: '/embed-panel'
      preLoaderRoute: typeof EmbedPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tailorkit/$': {
      id: '/api/tailorkit/$'
      path: '/api/tailorkit/$'
      fullPath: '/api/tailorkit/$'
      preLoaderRoute: typeof ApiTailorkitSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmbedPanelRoute: EmbedPanelRoute,
  ApiTailorkitSplatRoute: ApiTailorkitSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
